local _, ns = ...

-- =====================================================================
-- Postbox :: minimap mail icon
-- ---------------------------------------------------------------------
-- A replacement for the default "you have new mail" minimap indicator.
-- Behavioural spec: .dev/SPEC-MinimapIcon.md. The short version:
--
--   * Shows while HasNewMail() is true, hides when it is not -- the same
--     contract as MinimapCluster.IndicatorFrame.MailFrame, which this
--     suppresses while the feature is on by unregistering that frame's one
--     event (UPDATE_PENDING_MAIL), so it never Shows and nothing that hooks
--     its Show/Hide -- EllesmereUI relayouts on both -- is ever poked.
--     Suppression never reparents: ElvUI snapshots the frame's parent once
--     and restores it forever after. Disable re-registers the event and runs
--     Blizzard's own handler, restoring the default indicator intact.
--
--   * The button is UNNAMED on purpose. EllesmereUI's minimap module sweeps
--     named Buttons (and LibDBIcon10_* frames) parented to the Minimap into
--     its own drawer; a nameless button is structurally invisible to it, and
--     to the ProjectAzilroka-style collectors that key off names. Do not
--     "fix" this by naming the frame.
--
--   * Frame level is minimap + 20: above EllesmereUI's ping-blocker overlay
--     (+10) and ElvUI's click-handler child, level with EllesmereUI's own
--     indicators. Re-asserted on every re-layout because both hosts rebuild
--     the minimap at login and on profile switches.
-- =====================================================================

ns.MinimapButton = ns.MinimapButton or {}
local MB = ns.MinimapButton

local L = ns.L

local DEFAULTS = {
  enabled  = false,  -- turning it on changes visible UI; that is the user's call
  icon     = "letter",
  size     = 20,
  position = "TOPRIGHT", -- just inside the map's top-right corner: the spot
                         -- says "this replaced your mail icon" at first
                         -- glance. Blizzard's own spot stays one pick away.
  angle    = 45,     -- degrees, 0 = east, CCW; used when position is CUSTOM,
                     -- and kept in step with the corner presets otherwise
  accent   = false,
  -- Glow, pulse and shadow all on: the styled icon should look its best the
  -- moment the feature is switched on -- the switch-on IS the opt-in, and
  -- each piece has its own checkbox for anyone who wants it quieter.
  glow     = true,
  shadow   = true,
  pulse    = true,   -- the glow's slow breathe; shadows never pulse
  -- Arrival notification. Both off by default: a sound and a moving icon
  -- are the two things an addon can do that a player cannot ignore, so
  -- they are asked for rather than assumed.
  alertSound = false,
  alertFlash = false,
  lock     = false,  -- swallow shift-drag entirely: no accidental nudges
}

-- ONE dropdown, every placement, no second control to contradict it:
--
--   BLIZZARD     exactly where the default mail indicator sits -- restyle
--                without moving anything. The default for fresh installs.
--   corners      rim presets, as angles.
--   CUSTOM       wherever the user shift-dragged it ALONG the rim (`angle`).
--   FREE         wherever the user shift-dragged it ON SCREEN (`offsetX` /
--                `offsetY` from the minimap centre -- still anchored to the
--                minimap, so it follows the map through moves and scale).
--
-- Shift-drag keeps the dropdown honest instead of fighting it: dragging in
-- any rim mode turns the position into CUSTOM, dragging in FREE stays FREE,
-- and the options panel's controls are refreshed on drag-stop. This is a
-- MAIL INDICATOR in every mode; the spread of modes exists because a
-- player's ideal spot for it is not ours to decide.
local POSITION_ANGLES = {
  TOPRIGHT    = 45,
  TOPLEFT     = 135,
  BOTTOMLEFT  = 225,
  BOTTOMRIGHT = 315,
}

local function IsKnownPosition(position)
  return POSITION_ANGLES[position] ~= nil
    or position == "CUSTOM"
    or position == "FREE"
    or position == "BLIZZARD"
end

-- Two short-lived ancestors: 1.19.0 stored detachment AS a position
-- ("DETACHED"), 1.21.0 as a separate boolean. Both mean FREE now.
-- Idempotent, run by every reader that touches position -- cheaper than a
-- migration pass.
local function NormalizeSettings(prefs)
  if prefs.position == "DETACHED" or prefs.detached == true then
    prefs.position = "FREE"
  end
  prefs.detached = nil
  return prefs
end

local MEDIA = "Interface\\AddOns\\Postbox\\Media\\"

-- `aspect` is height/width for art that is not square: the stock envelope
-- atlas is a 19.5x15 slot and stretching it square gives it jowls. The three
-- Postbox glyphs are generated by .dev/tools/gen-minimap-assets.js -- bold
-- white-on-alpha silhouettes drawn for 16-28 px, all accent-tintable. A
-- stored id that no longer exists (earlier versions shipped more) falls back
-- to the envelope wherever ICONS is read.
local ICONS = {
  postbox  = { texture = MEDIA .. "minimap-envelope.tga", tintable = true },
  badge    = { texture = MEDIA .. "minimap-badge.tga", tintable = true },
  blizzard = { atlas = "ui-hud-minimap-mail-up", aspect = 15 / 19.5 },
  -- The painted set, sliced from Elliott's sheet by
  -- .dev/tools/slice-minimap-icons.js. Full-colour art: the accent option
  -- leaves these alone and tints only the glow. Retired ids (plate, stack,
  -- clean, mailbox) fall back to the default wherever ICONS is read.
  letter       = { texture = MEDIA .. "minimap-letter.tga" },
  sealed       = { texture = MEDIA .. "minimap-sealed.tga" },
  parcel       = { texture = MEDIA .. "minimap-parcel.tga" },
  seal         = { texture = MEDIA .. "minimap-seal.tga" },
  open         = { texture = MEDIA .. "minimap-open.tga" },
  scroll       = { texture = MEDIA .. "minimap-scroll.tga" },
  mailbag      = { texture = MEDIA .. "minimap-mailbag.tga" },
  quill        = { texture = MEDIA .. "minimap-quill.tga" },
  stamped      = { texture = MEDIA .. "minimap-stamped.tga" },
  weathered    = { texture = MEDIA .. "minimap-weathered.tga" },
  bundle       = { texture = MEDIA .. "minimap-bundle.tga" },
  satchel      = { texture = MEDIA .. "minimap-satchel.tga" },
  pillar       = { texture = MEDIA .. "minimap-pillar.tga" },
  stone        = { texture = MEDIA .. "minimap-stone.tga" },
  wood         = { texture = MEDIA .. "minimap-wood.tga" },
  gold         = { texture = MEDIA .. "minimap-gold.tga" },
  letterclean  = { texture = MEDIA .. "minimap-letterclean.tga" },
  stampedclean = { texture = MEDIA .. "minimap-stampedclean.tga" },
  parcelclean  = { texture = MEDIA .. "minimap-parcelclean.tga" },
  bundleclean  = { texture = MEDIA .. "minimap-bundleclean.tga" },
  pillarclean  = { texture = MEDIA .. "minimap-pillarclean.tga" },
  stoneclean   = { texture = MEDIA .. "minimap-stoneclean.tga" },
  woodclean    = { texture = MEDIA .. "minimap-woodclean.tga" },
  goldclean    = { texture = MEDIA .. "minimap-goldclean.tga" },
}

local GLOW_SCALE = 2.2

local function Settings()
  return ns.Store.EnsurePath("profile.minimap", DEFAULTS)
end

-------------------------------------------------------------
-- 1. Guarded reads of the mail state
--
-- On 12.x the client can hand back secret values in mail APIs; branching on
-- one raises. EllesmereUI's own indicator carries the same guards.
-------------------------------------------------------------

local function IsSecret(value)
  return type(issecretvalue) == "function" and issecretvalue(value)
end

local function MailWaiting()
  if type(HasNewMail) ~= "function" then return false end
  local ok, pending = pcall(HasNewMail)
  if not ok or IsSecret(pending) then return false end
  return pending and true or false
end

-- The client's three-sender readout is deliberately NOT used here any more:
-- the tooltip is served from the mail memory's snapshot, which knows counts,
-- senders and what is still waiting inside an already-opened mail. Mail
-- memory keeps its own reader for the arrival watch, where the triple is
-- the signal rather than the content.

-- The default indicator's own OnLoad stands down under this rule (special
-- game modes without mail notifications); a replacement must too.
local function NotificationsRuledOut()
  if not (C_GameRules and type(C_GameRules.IsGameRuleActive) == "function") then
    return false
  end
  local rule = Enum and Enum.GameRule and Enum.GameRule.IngameMailNotificationDisabled
  if not rule then return false end
  local ok, active = pcall(C_GameRules.IsGameRuleActive, rule)
  return ok and active == true
end

-------------------------------------------------------------
-- 2. The default indicator
-------------------------------------------------------------

-- The legacy MiniMapMailFrame global no longer exists on 12.x; the frame is
-- reachable only by this path.
local function DefaultIndicator()
  local cluster = _G.MinimapCluster
  local holder = cluster and cluster.IndicatorFrame
  return holder and holder.MailFrame or nil
end

-- A plain Hide() does not stick: UPDATE_PENDING_MAIL re-Shows the frame on
-- login, on new mail, and on every pending-mail re-sync. So suppression
-- takes the event away from the frame instead, which stops it EVER Showing.
--
-- Why not a Show hook that re-hides? That was the first implementation, and
-- it flickered EllesmereUI: EUI hooks both Show and Hide on this frame and
-- answers each with a full relayout of every minimap indicator and button
-- row, so hide-after-show cost two relayouts per mail event and visibly
-- blinked its mouseover-hidden elements. With the event unregistered the
-- frame stays silent and EUI is never poked at all -- which also keeps EUI's
-- own mail icon (driven by those same hooks) from popping up alongside ours
-- mid-session.
local suppressing = false

local function SetDefaultSuppressed(on)
  on = on == true
  if suppressing == on then return end
  local mail = DefaultIndicator()
  if not mail then return end
  suppressing = on

  if on then
    mail:UnregisterEvent("UPDATE_PENDING_MAIL")
    -- Hide() on an already-hidden frame fires nothing, so this pokes EUI's
    -- relayout hook at most once, at the moment the user flips the option.
    mail:Hide()
    return
  end

  -- Hand the event back, then run Blizzard's own handler once to resync --
  -- not Show(): the envelope texture inside the frame is only made visible
  -- after a notification flipbook completes, so a bare Show() would restore
  -- an empty frame. The handler re-derives everything from HasNewMail().
  mail:RegisterEvent("UPDATE_PENDING_MAIL")
  local handler = mail:GetScript("OnEvent")
  if handler then pcall(handler, mail, "UPDATE_PENDING_MAIL") end
end

-------------------------------------------------------------
-- 3. EllesmereUI skin mode
--
-- When EllesmereUI's minimap module is running, ITS mail icon is the mail
-- icon: it cannot be switched off in its options and it is resurfaced by
-- many of its layout passes. Fighting that is a losing game. So in that
-- situation Postbox does not draw a button -- it restyles EllesmereUI's
-- button in place (icon art, accent tint, glow) and leaves position and
-- size to EllesmereUI, which is what its own options already control.
--
-- The Blizzard frame IS still silenced in this mode (see Refresh): its
-- Show/Hide traffic is what EllesmereUI's relayout hooks answer, and each
-- answer flashes their mouseover-hidden button row for a beat. Starving the
-- event starves their event-driven visibility sync too, so Postbox performs
-- that sync itself -- SetShown(HasNewMail()), the same call their own code
-- makes -- while their layout passes keep agreeing from HasNewMail() direct.
--
-- The button is found by its `_indicatorKey == "_mail"` field. Everything
-- changed is snapshotted first and restored exactly on disable, and if a
-- future EllesmereUI stops exposing this shape the skin quietly never
-- applies and Postbox falls back to its own button.
-------------------------------------------------------------

local EUI_SKIN_MAX_TRIES = 8

-- `fallback` latches when the finder exhausts its tries while the module is
-- still a candidate: without the latch, every Refresh would re-enter the
-- candidate block and flip the default indicator's suppression off and on
-- around each mail event. Cleared on disable and on PLAYER_ENTERING_WORLD.
local euiSkin = { button = nil, saved = nil, applied = false,
                  tries = 0, timerArmed = false, fallback = false }

local function EuiMinimapProfile()
  local host = _G.EllesmereUI
  if not (host and host.Lite and type(host.Lite.GetAddon) == "function") then
    return nil
  end
  local ok, mm = pcall(function()
    local sub = host.Lite.GetAddon("EllesmereUIMinimap", true)
    return sub and sub.db and sub.db.profile and sub.db.profile.minimap
  end)
  if ok and type(mm) == "table" then return mm end
  return nil
end

-- Skin mode is a candidate whenever the module is loaded and its profile
-- does not say disabled. An unreadable profile counts as enabled: the module
-- ships enabled by default, and guessing "disabled" would flash Postbox's
-- own button at login before the profile arrives.
local function EuiSkinCandidate()
  if not (C_AddOns and type(C_AddOns.IsAddOnLoaded) == "function") then
    return false
  end
  if not C_AddOns.IsAddOnLoaded("EllesmereUIMinimap") then return false end
  local mm = EuiMinimapProfile()
  return not mm or mm.enabled ~= false
end

local RestoreEuiSkin -- forward: the finder restores an orphaned button on rebuild

local function FindEuiMailButton()
  local minimap = _G.Minimap
  local cached = euiSkin.button
  if cached and cached:GetParent() == minimap then return cached end

  if not minimap then return nil end
  local kids = { minimap:GetChildren() }
  for i = 1, #kids do
    local child = kids[i]
    if child and child ~= MB._button and child._indicatorKey == "_mail" then
      if euiSkin.button and euiSkin.button ~= child then
        -- EllesmereUI rebuilt its button mid-session. Restore the orphan
        -- verbatim -- it would otherwise keep our texture and its stood-down
        -- hover fields forever -- and drop the snapshot, which described the
        -- old frame, not this one.
        RestoreEuiSkin()
        euiSkin.saved = nil
      end
      euiSkin.button = child
      return child
    end
  end
end

local function ApplyEuiSkin()
  local btn = FindEuiMailButton()
  local icon = btn and btn._icon
  if not icon then return false end

  if not euiSkin.saved then
    local w, h = icon:GetSize()
    -- The atlas fields alone cannot restore a button whose _upAtlas was nil,
    -- so the icon's actual art is snapshotted alongside them.
    euiSkin.saved = { up = btn._upAtlas, over = btn._overAtlas, w = w, h = h,
                      atlas = icon:GetAtlas(), texture = icon:GetTexture() }
  end

  local prefs = Settings()
  local spec = ICONS[prefs.icon] or ICONS[DEFAULTS.icon]
  local r, g, b = 1, 1, 1
  if prefs.accent ~= false then r, g, b = ns.Theme.GetAccent() end

  if prefs.icon == "blizzard" then
    -- "Blizzard" here means EllesmereUI's stock look, which is the same art.
    local saved = euiSkin.saved
    btn._upAtlas, btn._overAtlas = saved.up, saved.over
    if saved.up then icon:SetAtlas(saved.up)
    elseif saved.atlas then icon:SetAtlas(saved.atlas)
    elseif saved.texture then icon:SetTexture(saved.texture) end
    icon:SetSize(euiSkin.saved.w, euiSkin.saved.h)
    icon:SetVertexColor(1, 1, 1)
  else
    -- Their OnEnter/OnLeave/OnMouseDown swap the icon atlas from these two
    -- fields; nil means those scripts stand down, which is exactly what a
    -- replaced texture needs. Restored verbatim on disable.
    btn._upAtlas, btn._overAtlas = nil, nil
    if spec.atlas then
      icon:SetAtlas(spec.atlas)
    else
      icon:SetTexture(spec.texture)
    end
    local side = math.max(10, math.min(btn:GetWidth(), btn:GetHeight()) - 6)
    icon:SetSize(side, side * (spec.aspect or 1))
    if spec.tintable then
      icon:SetVertexColor(r, g, b)
    else
      icon:SetVertexColor(1, 1, 1)
    end
  end

  local shadow = btn.__pbMailShadow
  if prefs.shadow == true then
    if not shadow then
      shadow = btn:CreateTexture(nil, "BACKGROUND", nil, -1)
      shadow:SetPoint("CENTER", icon, "CENTER", 0, -1)
      shadow:SetTexture(MEDIA .. "minimap-glow.tga")
      shadow:SetVertexColor(0, 0, 0)
      shadow:SetAlpha(0.9)
      btn.__pbMailShadow = shadow
    end
    shadow:SetSize(btn:GetWidth() * 1.3, btn:GetHeight() * 1.3)
    shadow:Show()
  elseif shadow then
    shadow:Hide()
  end

  local glow = btn.__pbMailGlow
  if prefs.glow == true then
    if not glow then
      glow = btn:CreateTexture(nil, "BACKGROUND")
      glow:SetPoint("CENTER", icon, "CENTER")
      glow:SetTexture(MEDIA .. "minimap-glow.tga")
      glow:SetBlendMode("ADD")
      btn.__pbMailGlow = glow
      local pulse = glow:CreateAnimationGroup()
      pulse:SetLooping("BOUNCE")
      local fade = pulse:CreateAnimation("Alpha")
      fade:SetFromAlpha(1)
      fade:SetToAlpha(0.55)
      fade:SetDuration(1.6)
      fade:SetSmoothing("IN_OUT")
      btn.__pbMailPulse = pulse
    end
    glow:SetSize(btn:GetWidth() * 1.6, btn:GetHeight() * 1.6)
    glow:SetVertexColor(r, g, b)
    glow:Show()
    if prefs.pulse ~= false then
      if not btn.__pbMailPulse:IsPlaying() then btn.__pbMailPulse:Play() end
    else
      btn.__pbMailPulse:Stop()
    end
  elseif glow then
    btn.__pbMailPulse:Stop()
    glow:Hide()
  end

  euiSkin.applied = true
  return true
end

RestoreEuiSkin = function()
  if not euiSkin.applied then return end
  euiSkin.applied = false

  local btn = euiSkin.button
  local saved = euiSkin.saved
  if not (btn and saved) then return end

  btn._upAtlas, btn._overAtlas = saved.up, saved.over
  local icon = btn._icon
  if icon then
    if saved.up then icon:SetAtlas(saved.up)
    elseif saved.atlas then icon:SetAtlas(saved.atlas)
    elseif saved.texture then icon:SetTexture(saved.texture) end
    icon:SetSize(saved.w, saved.h)
    icon:SetVertexColor(1, 1, 1)
  end
  if btn.__pbMailGlow then
    btn.__pbMailPulse:Stop()
    btn.__pbMailGlow:Hide()
  end
  if btn.__pbMailShadow then btn.__pbMailShadow:Hide() end
end

-- Skin mode starves the Blizzard frame's UPDATE_PENDING_MAIL (see Refresh),
-- which also starves the event-driven half of EllesmereUI's own visibility
-- sync -- so that half is performed here, with the exact call their sync
-- makes. Their periodic layout passes read HasNewMail() directly and agree.
local function SyncEuiButtonShown()
  local btn = euiSkin.button
  if not (btn and euiSkin.applied) then return end

  local waiting = MailWaiting()
  btn:SetShown(waiting)

  -- EllesmereUI anchors this button only inside its own layout pass, and
  -- only while the button is SHOWN -- their builder gives it no points at
  -- all. So after a login with no unread mail (their sync hid it before
  -- any layout ran) the button has no rect, and showing it here renders it
  -- nowhere. Their layout runs from their hooks on the Blizzard frame: one
  -- Show()/Hide() poke fires it -- sync, then anchor -- and their module
  -- alpha-zeroes that frame, so nothing is seen. Gated on the missing
  -- points, this fires at most once per session; anchors persist once set.
  if waiting and btn:GetNumPoints() == 0 then
    local mail = DefaultIndicator()
    if mail then
      pcall(mail.Show, mail)
      pcall(mail.Hide, mail)
    end
  end
end

-- The options panel asks this to decide which controls make sense: in skin
-- mode, position and size belong to EllesmereUI.
function MB.IsHostStyled()
  return EuiSkinCandidate() and not euiSkin.fallback
end

-------------------------------------------------------------
-- 4. Position on the rim
-------------------------------------------------------------

-- Round unless somebody says square. GetMinimapShape is the LibDBIcon-era
-- convention ElvUI implements; corner-rounded hybrid shapes are treated as
-- round, which errs toward keeping the button on the visible map edge.
-- EllesmereUI's minimap module defines no shape API at all, so its live
-- profile is read instead -- via Lite.GetAddon, because its SavedVariables
-- global is vestigial and wiped at load.
local function MinimapIsRound()
  if type(_G.GetMinimapShape) == "function" then
    local ok, shape = pcall(_G.GetMinimapShape)
    if ok and type(shape) == "string" then
      return shape ~= "SQUARE"
    end
  end
  local host = _G.EllesmereUI
  if host and host.Lite and type(host.Lite.GetAddon) == "function" then
    local ok, mm = pcall(function()
      local sub = host.Lite.GetAddon("EllesmereUIMinimap", true)
      return sub and sub.db and sub.db.profile and sub.db.profile.minimap
    end)
    if ok and type(mm) == "table" then
      return (mm.shape or "square") ~= "square"
    end
  end
  return true
end

-- The angle the button actually sits at: the corner preset's, or the
-- shift-dragged one when the position is CUSTOM.
local function CurrentAngle()
  local prefs = Settings()
  local preset = POSITION_ANGLES[prefs.position]
  if preset then return preset end
  return tonumber(prefs.angle) or DEFAULTS.angle
end

-- The rim point for the current angle: the ray from the minimap centre out to
-- the rim -- the circle's radius, or for a square minimap the ray's exit
-- through the square (radius / the larger direction component) -- then pulled
-- back inside by half the button plus a hair. This is an INDICATOR that lives
-- inside the map, not an addon launcher riding the edge.
local function RimOffset(minimap)
  local radius = (minimap:GetWidth() or 140) / 2
  local radians = math.rad(CurrentAngle())
  local cos, sin = math.cos(radians), math.sin(radians)

  local reach = radius
  if not MinimapIsRound() then
    reach = radius / math.max(math.abs(cos), math.abs(sin))
  end

  local size = tonumber(Settings().size) or DEFAULTS.size
  reach = math.max(0, reach - (size / 2 + 2))
  return cos * reach, sin * reach
end

local function Reposition(button)
  local minimap = _G.Minimap
  if not (button and minimap) then return end

  local prefs = NormalizeSettings(Settings())

  -- BLIZZARD: sit exactly where the default indicator sits, by anchoring to
  -- it -- the host UI keeps owning WHERE mail shows and we only own how it
  -- looks. The frame stays anchorable while hidden (our suppression hides
  -- it, its anchors survive). A client without the frame falls through to
  -- the rim so the icon is never lost.
  if prefs.position == "BLIZZARD" then
    local mail = DefaultIndicator()
    if mail then
      button:ClearAllPoints()
      button:SetPoint("CENTER", mail, "CENTER", 0, 0)
      button:SetFrameLevel((minimap:GetFrameLevel() or 2) + 20)
      return
    end
  end

  local x, y
  if prefs.position == "FREE" then
    x, y = tonumber(prefs.offsetX), tonumber(prefs.offsetY)
    if not (x and y) then
      -- First switch to FREE: hold the exact spot the icon already
      -- occupies, so the mode change moves nothing until the player drags.
      x, y = RimOffset(minimap)
      prefs.offsetX, prefs.offsetY = x, y
    end
  else
    x, y = RimOffset(minimap)
  end

  button:ClearAllPoints()
  button:SetPoint("CENTER", minimap, "CENTER", x, y)
  button:SetFrameLevel((minimap:GetFrameLevel() or 2) + 20)
end

local function AngleFromCursor()
  local minimap = _G.Minimap
  local centerX, centerY = minimap:GetCenter()
  if not centerX then return nil end
  local scale = minimap:GetEffectiveScale()
  if not scale or scale == 0 then return nil end
  local cursorX, cursorY = GetCursorPosition()
  local dx = cursorX / scale - centerX
  local dy = cursorY / scale - centerY
  if dx == 0 and dy == 0 then return nil end
  return math.deg(math.atan2(dy, dx)) % 360
end

-------------------------------------------------------------
-- 5. Look
-------------------------------------------------------------

local function ApplyLook(button)
  local prefs = Settings()
  local size = tonumber(prefs.size) or DEFAULTS.size
  button:SetSize(size, size)

  local spec = ICONS[prefs.icon] or ICONS[DEFAULTS.icon]
  local icon = button.icon
  icon:SetSize(size, size * (spec.aspect or 1))
  if spec.atlas then
    icon:SetAtlas(spec.atlas)
  else
    icon:SetTexture(spec.texture)
  end

  -- One accent switch for the whole element: the glyph (where the art is
  -- tintable) and the glow follow ns.Theme.GetAccent() together -- the
  -- EllesmereUI accent when that skin is active, Postbox's own otherwise.
  -- Untintable art keeps its colours and only the glow carries the accent.
  local r, g, b = 1, 1, 1
  if prefs.accent ~= false then
    r, g, b = ns.Theme.GetAccent()
  end
  if spec.tintable then
    icon:SetVertexColor(r, g, b)
  else
    icon:SetVertexColor(1, 1, 1)
  end

  local glow = button.glow
  glow:SetSize(size * GLOW_SCALE, size * GLOW_SCALE)
  glow:SetVertexColor(r, g, b)
  if prefs.glow == true then
    glow:Show()
    if prefs.pulse ~= false then
      if not button.pulse:IsPlaying() then button.pulse:Play() end
    else
      button.pulse:Stop()
    end
  else
    button.pulse:Stop()
    glow:Hide()
  end

  -- The shadow is the glow art in black at normal blend, a touch smaller
  -- and nudged down -- grounding rather than radiance. No pulse.
  local shadow = button.shadow
  shadow:SetSize(size * 1.8, size * 1.8)
  shadow:SetShown(prefs.shadow == true)

  Reposition(button)
end

-------------------------------------------------------------
-- 6. The button
-------------------------------------------------------------

local function ShowTooltip(button)
  GameTooltip:SetOwner(button, "ANCHOR_BOTTOMLEFT")

  -- One line per gesture, the gesture in gold and its effect in the hint
  -- grey -- scannable, and each line exists only while it is TRUE: the
  -- memory line goes when the option is off, the move line goes while the
  -- position is locked, and the alt line always says which way it toggles.
  local function ActionLine(actionKey, descKey)
    GameTooltip:AddLine(
      string.format("|cffffd100%s|r - %s", L[actionKey], L[descKey]),
      0.6, 0.6, 0.6, true)
  end

  -- Postbox describes the mailbox here, not the client. The default
  -- indicator's tooltip is "Unread mail from:" plus up to three bare names
  -- -- no counts, nothing about what is still waiting in a mail already
  -- opened, and it duplicated the breakdown below it. What the snapshot
  -- knows is strictly better, so it is the whole tooltip.
  local Memory = ns.MailMemory
  local state = Memory and type(Memory.MailboxSummary) == "function"
    and Memory.MailboxSummary() or nil

  GameTooltip:SetText(L["FRAME_TITLE"])

  if state and state.arrived then
    -- Green: good news. The accent belongs to selection and the orange to
    -- refusals; an arrival is neither (see the badge in Core/MailMemory).
    local pos = ns.Theme.Colors.positive
    GameTooltip:AddLine(L["MEMORY_NEW_SINCE"], pos[1], pos[2], pos[3])
    local from = state.newFrom
    if type(from) == "table" then
      for i = 1, #from do GameTooltip:AddLine(from[i], 1, 1, 1) end
    end
  end

  -- Each heading carries its own total, so the count is where the thing
  -- being counted is rather than stranded on a separate line.
  local function Breakdown(groups, heading, count, hr, hg, hb)
    if not groups then return end
    GameTooltip:AddLine(" ")
    GameTooltip:AddLine(string.format(heading, count), hr, hg, hb)
    local shown = math.min(#groups, 5)
    for i = 1, shown do
      GameTooltip:AddDoubleLine(groups[i].name, "x" .. groups[i].count,
        1, 1, 1, 0.75, 0.75, 0.78)
    end
    if #groups > shown then
      GameTooltip:AddLine(string.format(L["MEMORY_WAITING_MORE"], #groups - shown),
        0.6, 0.6, 0.63)
    end
  end

  if state and (state.groups or state.stuckGroups) then
    Breakdown(state.groups, L["MEMORY_WAITING_HEAD"], state.waiting,
      0.75, 0.75, 0.78)
    -- Its own heading in the orange a refusal wears everywhere else in the
    -- addon. Listing these under "waiting to collect" and then counting
    -- them again below read as twice the mail there actually was.
    local warn = ns.Theme.Colors.warning
    Breakdown(state.stuckGroups, L["MEMORY_STUCK_HEAD"], state.stuck,
      warn[1], warn[2], warn[3])
  elseif state then
    GameTooltip:AddLine(L["MEMORY_NOTHING_WAITING"], 0.75, 0.75, 0.78)
  else
    -- No snapshot (memory off, or this character has never opened a
    -- mailbox with Postbox installed): say only what the client knows.
    GameTooltip:AddLine(HAVE_MAIL or "", 0.75, 0.75, 0.78)
  end

  if Memory and type(Memory.SummaryText) == "function" then
    local summary = Memory.SummaryText()
    if summary then
      GameTooltip:AddLine(summary, 0.55, 0.55, 0.58, true)
    end
  end
  GameTooltip:AddLine(" ")

  local UIOpt = ns.MailboxUI
  if UIOpt and type(UIOpt.GetOption) == "function" and UIOpt.GetOption("mailMemory") then
    ActionLine("MINIMAP_TIP_ACT_CLICK", "MINIMAP_TIP_D_MEMORY")
  end
  ActionLine("MINIMAP_TIP_ACT_RIGHT", "MINIMAP_TIP_D_OPTIONS")
  local locked = Settings().lock
  if not locked then
    ActionLine("MINIMAP_TIP_ACT_DRAG", "MINIMAP_TIP_D_MOVE")
  end
  ActionLine("MINIMAP_TIP_ACT_ALT", locked and "MINIMAP_TIP_D_UNLOCK" or "MINIMAP_TIP_D_LOCK")
  GameTooltip:Show()
end

local function OnDragUpdate(button)
  local prefs = NormalizeSettings(Settings())

  -- FREE: the icon follows the cursor itself, in minimap-relative
  -- coordinates so it keeps riding the map through scale and position
  -- changes. Saved live, same as the rim drag.
  if prefs.position == "FREE" then
    local minimap = _G.Minimap
    local centerX, centerY = minimap:GetCenter()
    local scale = minimap:GetEffectiveScale()
    if not centerX or not scale or scale == 0 then return end
    local cursorX, cursorY = GetCursorPosition()
    prefs.offsetX = cursorX / scale - centerX
    prefs.offsetY = cursorY / scale - centerY
    Reposition(button)
    return
  end

  local angle = AngleFromCursor()
  if angle then
    prefs.position = "CUSTOM"
    prefs.angle = angle
    Reposition(button)
  end
end

local function Build()
  if MB._button then return MB._button end
  local minimap = _G.Minimap
  if not minimap then return nil end

  -- Unnamed: see the header comment before naming this frame.
  local button = CreateFrame("Button", nil, minimap)
  -- Unnamed, and parented to the MINIMAP rather than to anything of ours,
  -- so a skin looking for a Postbox ancestor would never find one. Said
  -- outright instead (Core/Skin_Modern.lua, IsOurs).
  button.__pbTooltipOwner = true
  button:Hide()
  button:RegisterForClicks("LeftButtonUp", "RightButtonUp")
  button:RegisterForDrag("LeftButton")
  -- A detached icon is placed by hand and must never be lost off-screen; on
  -- the rim the clamp simply never engages.
  button:SetClampedToScreen(true)

  local shadow = button:CreateTexture(nil, "BACKGROUND", nil, -1)
  shadow:SetPoint("CENTER", button, "CENTER", 0, -1)
  shadow:SetTexture(MEDIA .. "minimap-glow.tga")
  shadow:SetVertexColor(0, 0, 0)
  shadow:SetAlpha(0.9)
  shadow:Hide()
  button.shadow = shadow

  local glow = button:CreateTexture(nil, "BACKGROUND", nil, 0)
  glow:SetPoint("CENTER")
  glow:SetTexture(MEDIA .. "minimap-glow.tga")
  glow:SetBlendMode("ADD")
  glow:Hide()
  button.glow = glow

  local icon = button:CreateTexture(nil, "ARTWORK")
  icon:SetPoint("CENTER")
  button.icon = icon

  -- Hover feedback reuses the glow art faintly, so the hit target reads as a
  -- control without adding chrome.
  button:SetHighlightTexture(MEDIA .. "minimap-glow.tga", "ADD")
  local highlight = button:GetHighlightTexture()
  highlight:ClearAllPoints()
  highlight:SetPoint("CENTER")
  highlight:SetSize(DEFAULTS.size * GLOW_SCALE, DEFAULTS.size * GLOW_SCALE)
  highlight:SetAlpha(0.35)
  button.highlight = highlight

  -- A slow breathe on the glow while mail waits. BOUNCE alternates the fade
  -- direction each loop, so there is no snap at the ends.
  local pulse = glow:CreateAnimationGroup()
  pulse:SetLooping("BOUNCE")
  local fade = pulse:CreateAnimation("Alpha")
  fade:SetFromAlpha(1)
  fade:SetToAlpha(0.55)
  fade:SetDuration(1.6)
  fade:SetSmoothing("IN_OUT")
  button.pulse = pulse

  -- The arrival flash: the glow, breathing deeper for a few seconds.
  --
  -- Two earlier attempts and what each got wrong. A SCALE on the button
  -- jumped the icon, its shadow and its glow together -- movement reads as
  -- flicker. A halo in the OVERLAY layer sat ON TOP of the icon, washing
  -- out the very art it was meant to draw attention to.
  --
  -- This one lives in BACKGROUND, one sublevel above the standing glow and
  -- therefore still BEHIND the icon and its shadow, and it is barely wider
  -- than that glow. So the effect is not a new thing appearing: it is the
  -- existing halo swelling and settling. Where the player already runs a
  -- glow, this adds to it and recedes into it; where they do not, it rises
  -- from nothing and returns there. Either way nothing moves, nothing
  -- covers the icon, and the standing glow's own breathing loop is never
  -- touched -- it keeps running underneath throughout.
  local alert = button:CreateTexture(nil, "BACKGROUND", nil, 1)
  alert:SetPoint("CENTER")
  alert:SetTexture(MEDIA .. "minimap-glow.tga")
  alert:SetBlendMode("ADD")
  alert:SetAlpha(0)
  button.alert = alert

  local flash = alert:CreateAnimationGroup()
  -- Two slow swells, the second gentler than the first, and a long final
  -- fade: the tail is what makes it settle rather than stop. IN_OUT at both
  -- ends means there is no moment where the brightness changes abruptly.
  local phases = {
    { 0.00, 0.75, 1.10 },
    { 0.75, 0.28, 1.30 },
    { 0.28, 0.62, 1.00 },
    { 0.62, 0.00, 1.60 },
  }
  for i = 1, #phases do
    local phase = flash:CreateAnimation("Alpha")
    phase:SetFromAlpha(phases[i][1])
    phase:SetToAlpha(phases[i][2])
    phase:SetDuration(phases[i][3])
    phase:SetSmoothing("IN_OUT")
    phase:SetOrder(i)
  end
  -- Animations leave the region wherever they finished; the explicit zero
  -- is what guarantees no residue when the sequence ends or is stopped.
  flash:SetScript("OnFinished", function() alert:SetAlpha(0) end)
  flash:SetScript("OnStop", function() alert:SetAlpha(0) end)
  button.flash = flash

  button:SetScript("OnEnter", ShowTooltip)
  button:SetScript("OnLeave", function() GameTooltip:Hide() end)
  button:SetScript("OnClick", function(self, mouseButton)
    if IsShiftKeyDown() then return end -- shift is the drag modifier
    -- Alt-click toggles the position lock in place -- the same setting the
    -- options panel's checkbox owns, which is refreshed immediately so the
    -- two can never disagree. The tooltip re-renders so the line under the
    -- cursor tells the new truth.
    if IsAltKeyDown() then
      if mouseButton == "LeftButton" then
        MB.SetLocked(not MB.GetLocked())
        local Panel = ns.OptionsPanel
        if Panel and type(Panel.RefreshControls) == "function" then
          Panel.RefreshControls()
        end
        if GameTooltip:IsOwned(self) then ShowTooltip(self) end
      end
      return
    end
    if mouseButton == "RightButton" then
      -- Settings live behind the deliberate click; a stray left-click must
      -- never fling a window at the player.
      local Panel = ns.OptionsPanel
      if Panel and type(Panel.Toggle) == "function" then
        Panel.Toggle(self)
      end
      return
    end
    -- Left is the mail action: what the mailbox held when this character
    -- last saw it. Toggle itself declines while a real mailbox is open.
    local Memory = ns.MailMemory
    if Memory and type(Memory.Toggle) == "function" then
      Memory.Toggle(self)
    end
  end)

  -- Shift-drag anywhere on the rim; a plain drag is ignored so a click can
  -- never smear the position, and a locked icon ignores even shift. The
  -- angle is saved live, so releasing the button anywhere leaves the icon
  -- exactly where it looks.
  button:SetScript("OnDragStart", function(self)
    if not IsShiftKeyDown() then return end
    if Settings().lock then return end
    self:SetScript("OnUpdate", OnDragUpdate)
  end)
  button:SetScript("OnDragStop", function(self)
    self:SetScript("OnUpdate", nil)
    -- A drag can silently turn a corner preset into CUSTOM; if the options
    -- panel is open on screen, its controls should say so without needing
    -- to be closed and reopened.
    local Panel = ns.OptionsPanel
    if Panel and type(Panel.RefreshControls) == "function" then
      Panel.RefreshControls()
    end
  end)

  MB._button = button
  return button
end

-------------------------------------------------------------
-- 7. State
--
-- Off means OFF. While the setting is disabled this module's session
-- footprint is nothing at all: no frames, no event registrations, no touch
-- on the default indicator. The runtime below is brought up on enable and
-- torn back down on disable, so the only trace an enable-then-disable can
-- leave is the two hooks WoW provides no way to remove -- both of which are
-- guarded to dead code while inactive.
-------------------------------------------------------------

local Refresh -- forward: the event handlers below re-enter it

local function OnMailEvent()
  Refresh()
end

-- Re-derives everything on zone-in: both host UIs rebuild and resize the
-- minimap at login and on profile switches, which moves the rim. A loading
-- screen is also when a host rebuilds its buttons, so an exhausted finder
-- gets its tries back rather than staying in fallback forever.
local function OnEnterWorld()
  euiSkin.fallback = false
  euiSkin.tries = 0
  Refresh()
end

local runtimeActive = false

local function SetRuntimeActive(on)
  on = on == true
  if runtimeActive == on then return end
  runtimeActive = on

  if on then
    ns.Events.Register("UPDATE_PENDING_MAIL", OnMailEvent)
    ns.Events.Register("PLAYER_ENTERING_WORLD", OnEnterWorld)
    local minimap = _G.Minimap
    if minimap and not MB._sizeHooked then
      MB._sizeHooked = true
      hooksecurefunc(minimap, "SetSize", function()
        if runtimeActive and MB._button and MB._button:IsShown() then
          Reposition(MB._button)
        end
      end)
    end
    return
  end

  ns.Events.Unregister("UPDATE_PENDING_MAIL", OnMailEvent)
  ns.Events.Unregister("PLAYER_ENTERING_WORLD", OnEnterWorld)
end

Refresh = function()
  local prefs = Settings()

  if prefs.enabled ~= true or NotificationsRuledOut() then
    SetRuntimeActive(false)
    SetDefaultSuppressed(false)
    RestoreEuiSkin()
    euiSkin.tries = 0
    euiSkin.fallback = false
    if MB._button then MB._button:Hide() end
    return
  end

  SetRuntimeActive(true)

  -- One invariant while enabled: the default indicator is silenced, in BOTH
  -- modes. Skin mode once left the Blizzard frame alive so EllesmereUI's
  -- Show/Hide hooks on it could drive their icon -- but those hooks answer
  -- every mail event with a full relayout that resets their mouseover-hidden
  -- button row to full alpha and re-hides it on a deferred timer, a visible
  -- flash per AH purchase. Constant suppression generates zero Show/Hide
  -- traffic; the visibility sync those hooks performed is done below.
  SetDefaultSuppressed(true)

  -- EllesmereUI's minimap module running: restyle its icon in place, leave
  -- position and size to them.
  if EuiSkinCandidate() and not euiSkin.fallback then
    if MB._button then MB._button:Hide() end
    if ApplyEuiSkin() then
      euiSkin.tries = 0
      SyncEuiButtonShown()
      return
    end
    -- Their button is built a beat after login (and can lag a settings
    -- change); wait for it a few times before concluding their internals
    -- have changed shape and falling back to Postbox's own button. The
    -- latch matters: without it every later Refresh would re-enter this
    -- block and churn state around each mail event.
    if euiSkin.tries < EUI_SKIN_MAX_TRIES then
      euiSkin.tries = euiSkin.tries + 1
      if not euiSkin.timerArmed then
        euiSkin.timerArmed = true
        C_Timer.After(2, function()
          euiSkin.timerArmed = false
          Refresh()
        end)
      end
      return
    end
    euiSkin.fallback = true
  end

  RestoreEuiSkin()
  local button = Build()
  if not button then return end
  ApplyLook(button)

  -- Update the highlight to the configured size too; it is anchored art, not
  -- a child, so ApplyLook's SetSize does not reach it.
  local size = tonumber(prefs.size) or DEFAULTS.size
  button.highlight:SetSize(size * GLOW_SCALE, size * GLOW_SCALE)

  button:SetShown(MailWaiting())
end

MB.Refresh = Refresh

-- One line for /postbox debug. This exists because a transient "no icon"
-- report is undiagnosable after the fact: the fields below are everything
-- visibility depends on, captured at the moment the report is built.
function MB.Diagnose()
  return string.format(
    "runtime %s | suppressing %s | eui candidate %s applied %s tries %d fallback %s | own button %s | mail waiting %s",
    tostring(runtimeActive), tostring(suppressing),
    tostring((EuiSkinCandidate())), tostring(euiSkin.applied),
    euiSkin.tries, tostring(euiSkin.fallback),
    (MB._button and MB._button:IsShown()) and "shown" or "hidden/none",
    tostring((MailWaiting())))
end

-- Called by Skin_EllesmereUI.RefreshAccents so an accent retune repaints a
-- visible icon immediately rather than on the next mail event.
function MB.RefreshLook()
  if euiSkin.applied then
    ApplyEuiSkin()
    return
  end
  local button = MB._button
  if button and button:IsShown() then ApplyLook(button) end
end

-------------------------------------------------------------
-- 8. Options surface (consumed by Core/OptionsPanel.lua)
-------------------------------------------------------------

function MB.GetEnabled() return Settings().enabled == true end

function MB.SetEnabled(on)
  Settings().enabled = on == true
  Refresh()
end

function MB.Toggle()
  MB.SetEnabled(not MB.GetEnabled())
  ns.Print(L[MB.GetEnabled() and "MINIMAP_TOGGLE_ON" or "MINIMAP_TOGGLE_OFF"])
end

function MB.GetIcon()
  local id = Settings().icon
  return ICONS[id] and id or DEFAULTS.icon
end

-- The options panel's preview swatch reads the art through this rather than
-- knowing the ICONS table's shape.
function MB.GetIconSpec(id)
  return ICONS[id or MB.GetIcon()] or ICONS[DEFAULTS.icon]
end

function MB.SetIcon(id)
  if not ICONS[id] then return end
  Settings().icon = id
  Refresh()
end

function MB.GetIconSize()
  return tonumber(Settings().size) or DEFAULTS.size
end

function MB.SetIconSize(px)
  px = tonumber(px)
  if not px then return end
  Settings().size = px
  Refresh()
end

function MB.GetAccentTint() return Settings().accent ~= false end

function MB.SetAccentTint(on)
  Settings().accent = on == true
  Refresh()
end

function MB.GetGlow() return Settings().glow == true end

function MB.SetGlow(on)
  Settings().glow = on == true
  Refresh()
end

function MB.GetShadow() return Settings().shadow == true end

function MB.SetShadow(on)
  Settings().shadow = on == true
  Refresh()
end

function MB.GetPulse() return Settings().pulse ~= false end

function MB.SetPulse(on)
  Settings().pulse = on == true
  Refresh()
end

function MB.GetPosition()
  local position = NormalizeSettings(Settings()).position
  if IsKnownPosition(position) then return position end
  return DEFAULTS.position
end

function MB.SetPosition(position)
  if not IsKnownPosition(position) then return end
  local prefs = NormalizeSettings(Settings())
  prefs.position = position
  -- Keep the angle in step so a later switch to CUSTOM starts from where the
  -- icon already is instead of teleporting it.
  if POSITION_ANGLES[position] then prefs.angle = POSITION_ANGLES[position] end
  -- Leaving FREE drops its offset, so choosing FREE again later starts from
  -- wherever the icon is THEN, not a spot from a dead layout. Choosing FREE
  -- moves nothing: Reposition seeds the offset from the current spot and
  -- the next shift-drag goes anywhere.
  if position ~= "FREE" then
    prefs.offsetX, prefs.offsetY = nil, nil
  end
  Refresh()
end

-- Mail just arrived. Called by Core/MailMemory.lua, which owns the arrival
-- detection for the whole addon -- one witness, so the badge and the alert
-- can never disagree about what counts as new.
function MB.NotifyArrival()
  local prefs = Settings()

  if prefs.alertSound and type(PlaySound) == "function" and type(SOUNDKIT) == "table" then
    -- The client's own new-mail sound where it has one, its message chime
    -- otherwise; never a file of ours, so it obeys the player's sound
    -- settings like every other UI sound.
    local id = SOUNDKIT.UI_MAIL_ARRIVED or SOUNDKIT.TELL_MESSAGE
    if id then pcall(PlaySound, id) end
  end

  if prefs.alertFlash then
    local button = MB._button
    -- Only when the icon is actually on screen: an animation on a hidden
    -- frame is a promise nobody sees, and the icon shows on this same
    -- event anyway.
    if button and button:IsShown() and button.flash then
      -- Sized with the icon rather than at build time, so a size change
      -- between sessions cannot leave the halo the wrong scale. Barely
      -- wider than the standing glow: it is meant to read as that glow
      -- swelling, not as a second ring bleeding out past it.
      local size = tonumber(Settings().size) or DEFAULTS.size
      local reach = size * GLOW_SCALE * 1.04
      button.alert:SetSize(reach, reach)
      local pos = ns.Theme.Colors.positive
      button.alert:SetVertexColor(pos[1], pos[2], pos[3])
      if button.flash:IsPlaying() then button.flash:Stop() end
      button.flash:Play()
    end
  end
end

function MB.GetAlertSound()
  return Settings().alertSound == true
end

function MB.SetAlertSound(on)
  Settings().alertSound = on == true
end

function MB.GetAlertFlash()
  return Settings().alertFlash == true
end

function MB.SetAlertFlash(on)
  Settings().alertFlash = on == true
  -- Turning it off mid-flash leaves the icon wherever the animation was.
  local button = MB._button
  if not Settings().alertFlash and button and button.flash and button.flash:IsPlaying() then
    button.flash:Stop()
  end
end

function MB.GetLocked()
  return Settings().lock == true
end

function MB.SetLocked(on)
  Settings().lock = on == true
end

function MB.ResetPosition()
  local prefs = Settings()
  prefs.position = DEFAULTS.position
  prefs.angle = DEFAULTS.angle
  prefs.offsetX, prefs.offsetY = nil, nil
  Refresh()
end

-------------------------------------------------------------
-- 9. Init
-------------------------------------------------------------

function MB.Initialize()
  if MB._ready then return end
  MB._ready = true

  -- Same stand-down as the default indicator's own OnLoad: a game mode that
  -- rules out mail notifications gets no replacement for them either.
  if NotificationsRuledOut() then return end

  -- Refresh brings the runtime up only if the setting is on; with it off,
  -- this call is the module's LAST act of the session unless the user
  -- enables it from the options panel or /postbox minimap.
  Refresh()
end
