local _, ns = ...

-- =====================================================================
-- Postbox :: recipient manager window
-- ---------------------------------------------------------------------
-- Curation UI on top of Core/Recipients.lua. Postbox offers a recipient
-- for every character the game hands it -- guild, friends, recent allies,
-- Blizzard's account autocomplete, plus its own saved alts and mail
-- history. On an account with a decade of alts that list is mostly noise,
-- and this window is where it gets trimmed.
--
-- Two things shape the whole file:
--
-- 1. The state map is SPARSE (see Recipients.lua): only recipients with
--    non-default state have a stored row. So the list is the UNION of the
--    live sources and the stored rows, never just the stored table.
--
-- 2. The list can be several hundred rows on a big guild. Rows are pooled
--    AND virtualised: only the ~15 rows that fit the viewport are ever
--    created, and scrolling re-fills them. WoW cannot free a frame, so a
--    "one frame per recipient" list is a permanent cost paid by everyone
--    with a large guild.
--
-- Deleting is deliberately not offered for everything. A guild member or
-- autocomplete hit is regenerated by the next scan, so "delete" would be a
-- lie; Recipients.CanDelete says which is which and the button explains
-- itself when disabled.
-- =====================================================================

ns.RecipientManager = ns.RecipientManager or {}
local RM = ns.RecipientManager

local L = ns.L

-- Core/Theme.lua precedes this file in Postbox.toc and is not optional: it owns
-- every colour, font, gap and control height this window draws with, and it
-- owns the control plate the category bar and the sort direction button are
-- built from.
local Theme = ns.Theme
local M     = Theme.Metrics

-- EVERY metric below is a Theme.Metrics token or a stated exception to one.
-- This file used none of them: twelve pixels of window margin where the rest of
-- the addon insets by ten, its own control height, its own band padding, its
-- own tile height and its own scroll gutter -- so a window meant to read as
-- part of Postbox lined up with none of it.
local PAD        = M.inset
-- The one genuine exception. A recipient row is two stacked lines (name over a
-- metadata line) at a comfortable click height, which is neither the 44px mail
-- row nor the 18px list row; it is derived from its own contents rather than
-- from the ladder, and it is written out here so that stays visible.
local ROW_H      = 34
-- The row's own two push buttons. They sit inside a 34px row beside a checkbox,
-- so they are shorter than the window's controls and narrower than the ladder's
-- default button floor -- but their WIDTH still comes from the rendered caption,
-- between these bounds, because both captions are translated. The maximum is a
-- backstop against a pathological translation eating the name column, not a
-- size: nothing real reaches it.
local ROW_BTN_H     = 20
local ROW_BTN_MIN_W = 48
local ROW_BTN_MAX_W = 120
local CTRL_H     = M.controlHeight
local LIST_INSET = M.tightGap

-- Header band: one control row (search + sort) over one row of category tiles.
local BAND_PAD   = M.tightGap
-- The category tiles are a segmented switch over PERSISTENT window state, so
-- they take the theme's `segment` plate -- the one that carries a selected
-- underline -- and its height with it. See the plating section below.
local BAR_H      = M.segmentHeight
-- Favourites is an icon tile, not a word (see the bar build). BAR_STAR_W is its
-- width with no count on it: 2 * BAR_STAR_PAD + BAR_STAR_ICON, so the star can
-- be LEFT-anchored, look centred while it is alone, and not move when a count
-- appears beside it.
local BAR_STAR_ICON, BAR_STAR_PAD = M.iconSize, M.tightGap
local BAR_STAR_W  = BAR_STAR_ICON + BAR_STAR_PAD * 2
local BAR_COUNT_GAP = M.space.hair
-- Capped: the word tiles share whatever the star leaves them, and at the
-- minimum window width there is not much to give. The tile is measured from the
-- rendered string rather than given a fixed width, so no number ever clips.
local BAR_COUNT_CAP = 99
-- Tile to tile inside one dense strip: the ladder's smallest rung, and the same
-- gap Core/SendTab.lua's category bar uses, so the two bars tile identically.
local BAR_GAP    = M.space.hair

-- Widths, so no spacing token describes them.
-- Between the two bulk buttons at the foot of the window.
local ACTION_GAP    = 6
-- The sort group is ONE control in two halves: a toggle that names the field
-- and a square button that flips the direction. Both are built from
-- Theme.CreateButton and both are this tall, written once here so the pair
-- cannot drift apart -- the direction half used to be a flat plate at
-- M.tileHeight beside a push button, which on a stock UI is a bevelled button
-- two pixels from a flat fill: two controls, not one.
local SORT_TOGGLE_H = 22
local SORT_TOGGLE_W = 150
local SORT_DIR_W    = SORT_TOGGLE_H
-- The direction glyph inside that square. Small enough that the button still
-- reads as a button rather than as an arrow with a border round it.
local SORT_DIR_GLYPH = 12
-- Hair, not the padding rung: the two halves belong to each other, and this is
-- the same gap the category strips use between tiles in one dense bar.
local SORT_GROUP_W  = SORT_TOGGLE_W + M.space.hair + SORT_DIR_W

local DEFAULT_W, DEFAULT_H = 600, 480
-- The header is two rows tall, so the floor is higher than it was: below this
-- the list is not enough rows to be worth scrolling.
local MIN_W, MIN_H = 480, 360
local MAX_W, MAX_H = 1000, 800

local ADD_POPUP    = "POSTBOX_RM_ADD"
local DELETE_POPUP = "POSTBOX_RM_DELETE"
local BULK_POPUP   = "POSTBOX_RM_BULK"
local NOTE_POPUP   = "POSTBOX_RM_NOTE"
local NOTICE_POPUP = "POSTBOX_RM_NOTICE"

-- The live sources, in the order a row's PRIMARY label is attributed.
--
-- A recipient now belongs to every source that holds them -- your guildmate who
-- is also a friend and whom you mailed yesterday is in all three -- so this
-- order no longer decides membership, only which single word the row's meta
-- line leads with and how the Category sort ranks it. "Alt" beats "guild" beats
-- "friend" because that is the order of how much the fact tells you about the
-- person.
local BUCKETS = { "alts", "guild", "friends", "recent", "grouped" }
local BUCKET_LABEL = {
  alts    = "CONTACT_ALTS",
  guild   = "CONTACT_GUILD",
  friends = "CONTACT_FRIENDS",
  recent  = "CONTACT_RECENT",
  grouped = "CONTACT_RECENTLY_GROUPED",
}
local RANK_MANUAL = #BUCKETS + 1
local RANK_SAVED  = #BUCKETS + 2

-- Middle dot, in the palette's own disabled grey rather than a hand-picked
-- one. Built once at load: Core/Theme.lua precedes this file in the TOC.
local SEPARATOR = " " .. Theme.Colorize("textDisabled", "\194\183") .. " "

-------------------------------------------------------------
-- Category filters
--
-- The Send tab has the same bar under its recipient field, so the two windows
-- read as one product: the same categories in the same order, Favourites as a
-- star tile on the left, All on the right. Hidden is the one addition -- with
-- several hundred recipients, a name you hid last month is otherwise
-- unreachable.
--
-- EVERY CATEGORY IS NOW EXACT. It used to be best-effort: ContactService
-- de-duplicated across buckets, so a guildmate you had mailed came back in
-- `recent` and never in `guild`, and Guild listed the half of your guild you
-- never write to. A name now carries membership of every source it belongs to,
-- so Guild is your guild, Friends is your friends, and the apology the tile
-- tooltip used to carry (RM_CAT_TIP_APPROX) is gone rather than translated.
--
-- Recent means MAIL HISTORY and nothing else. People you recently grouped with
-- are a different fact about a different set of people; they keep their own
-- label on the row and are reachable under All.
--
-- `match` reads only fields Collect writes onto the entry, so filtering never
-- touches the data layer and never triggers a roster scan.
--
-- `source` names the ContactService source a category is a view of, where it is
-- one. It is what lets an empty category explain itself -- "you are not in a
-- guild" rather than "nothing in this list yet". See EmptyText.
-------------------------------------------------------------
local CATEGORIES = {
  { id = "favourites", labelKey = "CONTACT_FAVORITES", star = true,
    match = function(entry) return entry.fav == true end },
  { id = "recent", labelKey = "CONTACT_RECENT", source = "recent",
    match = function(entry) return entry.cats.recent end },
  { id = "alts", labelKey = "CONTACT_ALTS", source = "alts",
    match = function(entry) return entry.cats.alts end },
  { id = "friends", labelKey = "CONTACT_FRIENDS", source = "friends",
    match = function(entry) return entry.cats.friends end },
  { id = "guild", labelKey = "CONTACT_GUILD", source = "guild",
    match = function(entry) return entry.cats.guild end },
  { id = "hidden", labelKey = "RM_FILTER_HIDDEN",
    match = function(entry) return entry.hidden == true end },
  -- No `match`: All is the absence of a filter, not a predicate over entries.
  { id = "all", labelKey = "RM_FILTER_ALL" },
}

local CATEGORY_BY_ID = {}
for _, category in ipairs(CATEGORIES) do CATEGORY_BY_ID[category.id] = category end

-- Filters whose membership changes the moment a row is favourited or hidden.
-- A toggle under one of these has to re-filter rather than merely repaint: the
-- row that just changed no longer belongs in the list it is sitting in.
local STATEFUL_FILTERS = { favourites = true, hidden = true }

-------------------------------------------------------------
-- Sort fields
--
-- `desc` is the direction the field is most useful in on first pick, not a
-- fixed direction: every field reverses. Level and last-played default to
-- highest/most-recent first because "what can I get rid of" is answered from
-- the bottom of those lists.
-------------------------------------------------------------
local SORTS = {
  { id = "name",     nameKey = "RM_SORT_NAME",     desc = false },
  { id = "category", nameKey = "RM_SORT_CATEGORY", desc = false },
  { id = "level",    nameKey = "RM_SORT_LEVEL",    desc = true },
  { id = "lastSeen", nameKey = "RM_SORT_LASTSEEN", desc = true },
}

local SORT_BY_ID = {}
for _, sort in ipairs(SORTS) do SORT_BY_ID[sort.id] = sort end

-- An arrow can only say "up" or "down"; it cannot say whether up means A-to-Z
-- or level 1 first. The tooltip spells the current direction out in words.
local SORT_DIRECTION_KEY = {
  name     = { "RM_SORT_DIR_NAME_ASC",     "RM_SORT_DIR_NAME_DESC" },
  category = { "RM_SORT_DIR_CATEGORY_ASC", "RM_SORT_DIR_CATEGORY_DESC" },
  level    = { "RM_SORT_DIR_LEVEL_ASC",    "RM_SORT_DIR_LEVEL_DESC" },
  lastSeen = { "RM_SORT_DIR_LASTSEEN_ASC", "RM_SORT_DIR_LASTSEEN_DESC" },
}

-------------------------------------------------------------
-- Small utilities
-------------------------------------------------------------

local function Recipients() return ns.Recipients end

local function Lower(text)
  if ns.Helpers and ns.Helpers.Lower then return ns.Helpers.Lower(text) end
  return string.lower(tostring(text or ""))
end

local function Trim(text)
  if ns.Helpers and ns.Helpers.NormalizeText then return ns.Helpers.NormalizeText(text) end
  return (tostring(text or ""):gsub("^%s*(.-)%s*$", "%1"))
end

-- Guarded like the rest of the addon guards Blizzard globals: a missing time()
-- degrades to "no relative timestamp" rather than erroring in a refresh.
local function Now()
  if type(time) ~= "function" then return nil end
  local ok, value = pcall(time)
  if ok and type(value) == "number" then return value end
  return nil
end

local function FormatLastSeen(stamp)
  local now = Now()
  if type(stamp) ~= "number" or stamp <= 0 or not now then return nil end
  local diff = now - stamp
  if diff < 0 then diff = 0 end
  local days = math.floor(diff / 86400)
  if days <= 0 then return L["RM_LAST_TODAY"] end
  if days == 1 then return L["RM_LAST_YESTERDAY"] end
  if days < 60 then return L("RM_LAST_DAYS", days) end
  if days < 365 then return L("RM_LAST_MONTHS", math.floor(days / 30)) end
  return L("RM_LAST_YEARS", math.floor(days / 365))
end

-- `name` identifies the character (full address, realm half included); `text`,
-- when given, is what gets wrapped in the colour code. See
-- ContactService.GetClassColoredName.
local function ClassColored(name, text)
  local CS = ns.ContactService
  if CS and type(CS.GetClassColoredName) == "function" then
    local ok, colored = pcall(CS.GetClassColoredName, name, text)
    if ok and type(colored) == "string" and colored ~= "" then return colored end
  end
  return text or name
end

-- "Bob-Draenor" -> class-coloured "Bob" plus a grey realm half, so the realm
-- never competes with the name for attention.
--
-- The class is looked up by the WHOLE display string, not by the short half:
-- ContactService keys its cache on (name, realm), so looking up "Bob" alone
-- would ask about Bob on the player's own realm and colour a different person's
-- class onto this row.
local function DecorateName(display)
  local text = tostring(display or "")
  local short, realm = text:match("^([^%-]+)%-(.+)$")
  if short then
    return ClassColored(text, short) .. Theme.Colorize("textSecondary", "-" .. realm)
  end
  return ClassColored(text)
end

-- The character's class, in the player's language.
--
-- The class-coloured name only conveys a class to someone who knows the twelve
-- colours by sight, so the meta line spells it out. ContactService keeps its
-- class-token cache private and exposes only GetClassColoredName, so the class
-- is recovered from the colour code that function wraps the name in. The
-- reverse map is built from the client's own class colours using the same
-- formatting the colour code uses, which makes a hit an exact match rather
-- than a nearest-colour guess -- and a miss simply means no class is shown.
local classByColor

local function ClassColorKey(r, g, b)
  if type(r) ~= "number" or type(g) ~= "number" or type(b) ~= "number" then return nil end
  return string.format("%02x%02x%02x", r * 255, g * 255, b * 255)
end

local function ClassColorMap()
  if classByColor then return classByColor end
  classByColor = {}

  if type(LOCALIZED_CLASS_NAMES_MALE) ~= "table" then return classByColor end

  for token, localized in pairs(LOCALIZED_CLASS_NAMES_MALE) do
    local r, g, b
    if C_ClassColor and type(C_ClassColor.GetClassColor) == "function" then
      local ok, color = pcall(C_ClassColor.GetClassColor, token)
      if ok and type(color) == "table" then r, g, b = color.r, color.g, color.b end
    end
    if not r and type(RAID_CLASS_COLORS) == "table" and type(RAID_CLASS_COLORS[token]) == "table" then
      local color = RAID_CLASS_COLORS[token]
      r, g, b = color.r, color.g, color.b
    end
    local key = ClassColorKey(r, g, b)
    if key then classByColor[key] = localized end
  end

  return classByColor
end

-- nil when nothing has cached a class for this name -- an offline guild member
-- the roster has not returned yet, or a bare mail correspondent.
local function ClassName(display)
  local text = tostring(display or "")
  local short = text:match("^([^%-]+)")
  if not short or short == "" then return nil end
  -- Identified by the full display string, coloured as the short half, for the
  -- same reason as DecorateName: the cache is keyed on (name, realm).
  local colored = ClassColored(text, short)
  if colored == short then return nil end
  -- "|caarrggbb": skip the two alpha digits, keep the six colour ones.
  local key = colored:match("^|c%x%x(%x%x%x%x%x%x)")
  if not key then return nil end
  return ClassColorMap()[string.lower(key)]
end

-- Whether a level and a last-played time can EVER be known for this recipient.
--
-- They come from PostboxDB.altMeta, written when one of the player's own
-- characters logs in. No API reads an offline character's level, so for a guild
-- member, a friend or a mail correspondent the answer is not "not recorded
-- yet", it is "never" -- and printing "no data" on three hundred guild rows is
-- a placeholder that can never resolve. Only the player's own characters get
-- the note, because only there does the absence mean something and end.
local function TracksActivity(entry)
  return entry.cats.alts == true or entry.level ~= nil or entry.lastSeen ~= nil
end

-- Whether to flag "no current source offers this name any more". Display only,
-- never an action.
--
-- ONE definition, because four places need the answer -- the collect pass, the
-- post-bulk resync, the favourite toggle and the Hide tick -- and four readings
-- of the same rule is how the row under the cursor ends up contradicting the
-- row beside it. Hidden and manual entries are excluded: a hidden recipient is
-- still perfectly real, and a manual add for another realm would be
-- permanently "stale" by construction.
local function StaleFor(entry)
  return (RM._sourcesComplete and not entry.live
          and not entry.hidden and not entry.manual) and true or false
end

-- No `preferredIndex` on any dialog in this file, deliberately. It was a taint
-- mitigation that asked StaticPopup for the last dialog frame; 12.x's rewritten
-- StaticPopup does not read the field and no longer defines
-- STATICPOPUP_NUMDIALOGS, so every one of them was writing nil. See
-- Core/CollectTab.lua's fuller note.
local function Notice(message)
  local text = tostring(message or "")
  if type(StaticPopup_Show) == "function" and type(StaticPopupDialogs) == "table" then
    if not StaticPopupDialogs[NOTICE_POPUP] then
      StaticPopupDialogs[NOTICE_POPUP] = {
        text = "%s",
        button1 = L["POPUP_OK"],
        timeout = 0,
        whileDead = true,
        hideOnEscape = true,
      }
    end
    StaticPopup_Show(NOTICE_POPUP, text)
    return
  end
  ns.Print(text)
end

-- StaticPopup's edit box has moved around between clients; try every shape
-- before giving up rather than erroring inside a dialog handler.
local function PopupEditBox(dialog)
  if type(dialog) ~= "table" then return nil end
  if dialog.editBox then return dialog.editBox end
  if type(dialog.GetEditBox) == "function" then
    local ok, box = pcall(dialog.GetEditBox, dialog)
    if ok and box then return box end
  end
  local name = dialog.GetName and dialog:GetName()
  if name then return _G[name .. "EditBox"] end
  return nil
end

local function ToggleSound(on)
  if type(PlaySound) ~= "function" or type(SOUNDKIT) ~= "table" then return end
  local kit = on and SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON
                 or SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_OFF
  if kit then pcall(PlaySound, kit) end
end

-------------------------------------------------------------
-- Artwork
--
-- Atlases are preferred over texture paths where one exists: they are cut from
-- the modern high-resolution sheets and stay crisp at the sizes this window
-- uses, where the legacy standalone .blp files visibly soften.
--
-- They are also PROBED, never assumed. SetAtlas with an unknown name does not
-- error -- it clears the texture and leaves an empty square, which would be a
-- silent, client-version-dependent hole in the UI. C_Texture.GetAtlasInfo
-- settles it up front, and anything unresolved falls back to a texture path
-- that has shipped since vanilla.
-------------------------------------------------------------
local function AtlasExists(name)
  if type(name) ~= "string" or name == "" then return false end
  local getter = (C_Texture and C_Texture.GetAtlasInfo) or GetAtlasInfo
  if type(getter) ~= "function" then return false end
  local ok, info = pcall(getter, name)
  return ok and info ~= nil
end

-- The favourite star.
--
-- The old artwork was `Interface\Common\FavoritesIcon` at 18px with the off
-- state expressed as "the same star, desaturated and faint" -- two states that
-- differ only in intensity, which is exactly what is hard to read at a glance
-- in a list of several hundred rows.
--
-- The auction house's favourite pair is used instead when the client has it:
-- a filled gold star for on and a hollow outline for off. The states then
-- differ in SHAPE first and colour second, which survives both a dim host UI
-- and a colour-blind eye.
--
-- Neither state is ever faded. "Not a favourite" and "no favourites yet" are
-- both perfectly ordinary states of a working control, and a greyed-out icon
-- cannot be told apart from a disabled one, a half-loaded one, or a bug.
local STAR_ATLAS = { on = "auctionhouse-icon-favorite", off = "auctionhouse-icon-favorite-off" }
local STAR_TEXTURE = "Interface\\Common\\FavoritesIcon"
-- One token, read by this window and by Core/SendTab.lua's picker. Both files
-- used to carry the triple literally, each with a comment naming the other.
local STAR_EMPTY_TINT = ns.Core.UI.Theme.IconTints.starEmpty

local starAtlas, starProbed

local function StarAtlas()
  if not starProbed then
    starProbed = true
    -- Both or neither: an atlas star paired with a legacy outline would be two
    -- unrelated shapes sitting in the same column.
    if AtlasExists(STAR_ATLAS.on) and AtlasExists(STAR_ATLAS.off) then
      starAtlas = STAR_ATLAS
    end
  end
  return starAtlas
end

-- `on` true draws the filled gold star, false the hollow outline. Used for the
-- per-row toggle and for the Favourites tile alike, which is why there is no
-- third "dimmed" state: the tile with nothing in it shows the same outline star
-- a row that is not a favourite shows, at the same full opacity.
local function SetStarArt(texture, on)
  if not texture then return end
  local filled = on and true or false
  local atlas = StarAtlas()

  texture:SetDesaturated(false)
  texture:SetAlpha(1)

  if atlas then
    texture:SetAtlas(filled and atlas.on or atlas.off, false)
    if filled then
      texture:SetVertexColor(1, 1, 1, 1)
    else
      -- A cool near-white outline: unmistakably "not set" without reading as
      -- another shade of gold.
      texture:SetVertexColor(STAR_EMPTY_TINT[1], STAR_EMPTY_TINT[2], STAR_EMPTY_TINT[3], 1)
    end
    return
  end

  texture:SetTexture(STAR_TEXTURE)
  if filled then
    texture:SetVertexColor(1, 1, 1, 1)
  else
    -- No outline variant in the legacy asset, so the off state falls back to a
    -- colourless star -- still at full opacity, so it reads as a star that is
    -- not set rather than a star that failed to draw.
    texture:SetDesaturated(true)
    texture:SetVertexColor(STAR_EMPTY_TINT[1], STAR_EMPTY_TINT[2], STAR_EMPTY_TINT[3], 1)
  end
end

-- The sort direction arrow. Blizzard's own sortable column headers use
-- `UI-SortArrow` flipped vertically for the opposite direction; that is the
-- fallback, with the atlas pairs tried first.
local ARROW_ATLASES = {
  { up = "auctionhouse-ui-sortarrow-up", down = "auctionhouse-ui-sortarrow-down" },
  { up = "uitools-icon-chevron-up",      down = "uitools-icon-chevron-down" },
}
local ARROW_TEXTURE = "Interface\\Buttons\\UI-SortArrow"

local arrowAtlas, arrowProbed

local function ArrowAtlas()
  if not arrowProbed then
    arrowProbed = true
    for _, pair in ipairs(ARROW_ATLASES) do
      if AtlasExists(pair.up) and AtlasExists(pair.down) then
        arrowAtlas = pair
        break
      end
    end
  end
  return arrowAtlas
end

local function SetArrowArt(texture, up)
  if not texture then return end
  local atlas = ArrowAtlas()
  if atlas then
    texture:SetTexCoord(0, 1, 0, 1)
    texture:SetAtlas(up and atlas.up or atlas.down, false)
    return
  end
  texture:SetTexture(ARROW_TEXTURE)
  -- The asset's arrow occupies the left 0.5625 of the sheet and points up in
  -- its natural orientation; the down arrow is the same crop mirrored in Y.
  if up then
    texture:SetTexCoord(0, 0.5625, 0, 1)
  else
    texture:SetTexCoord(0, 0.5625, 1, 0)
  end
end

-------------------------------------------------------------
-- Category tile / direction button plating
--
-- Theme.CreatePlate, and nothing of this window's own.
--
-- This was the THIRD hand-rolled plate in the addon and the one furthest
-- outside the design system. It painted `_bg:SetColorTexture(1, 1, 1, fill)` at
-- 0.10 / 0.17 / 0.26 -- the same defect the Send tab's bar was reported for:
-- white at a tenth to a quarter of an alpha is 74% to 90% see-through, so under
-- a host UI whose window follows the user's own opacity the game world rendered
-- through the filter bar. It also carried three text colours of its own and a
-- fourth gold ({1.00, 0.82, 0.30}) that was neither the brand accent nor the
-- host UI's, so a window that is supposed to read as part of Postbox had its
-- own palette.
--
-- All of that is the factory's now: a ladder that rises in colour AND alpha
-- together (0.94 idle to 0.99 selected, so the more prominent state is always
-- the more substantial one), one ring, one bevel, one hover wash, and captions
-- in the accent tones derived from whichever accent is live.
--
-- The category tiles take the `segment` variant, which carries the selected
-- underline. That is the one place this bar deliberately differs from the Send
-- tab's, which takes `tile`: there "active" means "this list is open right now"
-- and lasts a moment, whereas here it is persistent state the whole window is
-- filtered by, and fill plus caption tone alone is not emphatic enough to
-- explain why a 316-name list is showing twelve rows.
-------------------------------------------------------------

-- The factory owns fill, ring, bevel, hover wash and caption tone. The one fact
-- it cannot know is that a category is EMPTY -- a property of the data, not of
-- the control -- so that caption is re-tinted after every repaint the factory
-- makes, including the hover repaints it installs itself.
local function TintEmptyCaption(tile)
  if tile and tile.Text and tile._empty and not tile._active then
    -- Nothing in this category. Still clickable: the empty state it lands on
    -- explains the category better than a disabled button would.
    Theme.SetColor(tile.Text, "textDisabled")
  end
end

local function StyleTile(tile)
  if not tile then return end

  -- The star tile with favourites behind it is `flagged`: one step up from
  -- idle and no more. Active still wins -- "this is the filter the list is
  -- under" is the more urgent fact, and the gold count beside the star says
  -- the rest.
  Theme.SetPlateFlagged(tile, tile._starTile and not tile._empty)
  -- Last, and the only call here that paints: SetPlateSelected honours a
  -- host-UI skin's __setSelectedOverride, after which the skin owns the whole
  -- visual and our plate art is retired for good.
  Theme.SetPlateSelected(tile, tile._active and true or false)
  TintEmptyCaption(tile)
end

-- Count text for the Favourites tile. nil means "show no number", which is the
-- empty state: a bare "0" would be one more thing to read where the hollow star
-- has already said it.
local function TileCountText(count)
  if not count or count <= 0 then return nil end
  if count > BAR_COUNT_CAP then return BAR_COUNT_CAP .. "+" end
  return tostring(count)
end

-- Sizes the star tile around its count. The width is derived from the rendered
-- string, so the bar's own layout pass has to run again afterwards -- see
-- UpdateCategoryBar.
local function SetTileCount(tile, count)
  if not tile or not tile.Count then return end
  local text = TileCountText(count)
  if text then
    tile.Count:SetText(text)
    tile.Count:Show()
    tile:SetWidth(BAR_STAR_W + BAR_COUNT_GAP + math.ceil(tile.Count:GetStringWidth() or 0))
  else
    tile.Count:Hide()
    tile:SetWidth(BAR_STAR_W)
  end
end

-- The plate itself, shared by the category tiles and the sort direction button.
-- Deliberately not tagged __postboxButton -- the host-UI skins restyle the
-- addon's push buttons, and these are flat plates that would come back as
-- full-size buttons. Theme.CreatePlate does not tag them either; the art it
-- creates goes into `__pbPlateArt`, which is what a skin retires instead.
--
-- `variant` is a Theme.PlateVariants key: "segment" for the category tiles,
-- which carry the selected underline, "tile" for the sort direction button,
-- which has no selected state to underline.
--
-- HookScript, never SetScript: the factory installs the hover repaint on
-- OnEnter/OnLeave, and replacing those is how a plate silently stops repainting
-- on hover. The hooks run after it, which is what the empty-caption re-tint
-- needs.
local function CreateTile(parent, variant)
  local tile = Theme.CreatePlate(parent, variant)

  tile:HookScript("OnEnter", function(self)
    TintEmptyCaption(self)
    if self._onEnter then self._onEnter(self) end
  end)
  tile:HookScript("OnLeave", function(self)
    TintEmptyCaption(self)
    GameTooltip:Hide()
  end)

  StyleTile(tile)
  return tile
end

-------------------------------------------------------------
-- Data collection
--
-- Returns entries, total, hiddenCount, favouriteCount.
--
-- Every entry is:
--   key, display, search, sortName, category, rank, cats,
--   live, hidden, fav, manual, note, level, lastSeen, faction, stale
-------------------------------------------------------------
local function Collect()
  local R = Recipients()
  local entries, byKey = {}, {}
  if not R then return entries, 0, 0, 0 end

  local CS = ns.ContactService

  local buckets
  if CS and type(CS.BuildSuggestions) == "function" then
    -- includeHidden, and this is the ONE caller that passes it for browsing.
    --
    -- This window is the curation UI: it is where a hidden recipient is found
    -- and brought back. Without this the live sources arrived pre-filtered, so
    -- every hidden name reached the list only through the stored-state overlay
    -- below, with no source and no category -- and the window then relabelled
    -- your hidden guildmate "Saved", refused to find them under the Guild
    -- filter, and printed "Not in any current list" on the row the moment you
    -- unticked Hide. All four of those were the same missing argument.
    local ok, result = pcall(CS.BuildSuggestions, "", { includeHidden = true })
    if ok and type(result) == "table" then buckets = result end
  end
  buckets = buckets or {}

  -- STALE DETECTION SAFETY GATE.
  --
  -- The guild roster and the friends list load asynchronously and return an
  -- empty list on a cold call. Marking "not returned this pass" as stale would
  -- flag the user's entire guild the first time the window is opened after a
  -- login. A stored row carries no record of which source it came from, so
  -- staleness can only be decided once every source that COULD hold the name
  -- has answered.
  --
  -- ContactService decides that, per source, because it is the only thing that
  -- knows whether a request is still in flight. The old test here was "all five
  -- lists are non-empty", which is false forever for anyone with no guild, no
  -- friends or no mail history -- so RM_META_STALE, the single most useful
  -- sentence this window has, was invisible to most of the people it was
  -- written for.
  local sourcesComplete = true
  if CS and type(CS.SourcesReady) == "function" then
    local ok, ready = pcall(CS.SourcesReady)
    sourcesComplete = ok and ready and true or false
  end
  -- Set before the entry pass rather than after it: StaleFor reads it.
  RM._sourcesComplete = sourcesComplete

  local function Entry(key)
    local entry = byKey[key]
    if not entry then
      entry = { key = key, cats = {}, rank = RANK_SAVED }
      byKey[key] = entry
      entries[#entries + 1] = entry
    end
    return entry
  end

  for rank, bucket in ipairs(BUCKETS) do
    local list = buckets[bucket]
    if type(list) == "table" then
      for _, name in ipairs(list) do
        if type(name) == "string" and name ~= "" then
          local key = R.Key(name)
          if key ~= "" then
            local entry = Entry(key)
            entry.live = true
            entry.cats[bucket] = true
            -- Buckets already hold addresses in the source's own spelling
            -- (ContactService.BuildSuggestions), so this is a valid To: value
            -- as it stands. Recipients.Display would rebuild the same string
            -- from the key, but only by scanning every saved alt table, and
            -- that scan repeated once per guild member is not free.
            entry.liveName = entry.liveName or name
            if rank < entry.rank then
              entry.rank = rank
              entry.category = L[BUCKET_LABEL[bucket]]
            end
          end
        end
      end
    end
  end

  -- The curation overlay. Rows exist only for recipients that carry non-default
  -- state, so this ADDS the ones no live source returned (hidden alts from a
  -- realm you no longer play, manual additions, notes) and annotates the rest.
  R.ForEach(function(key, row)
    local entry = Entry(key)
    entry.hidden = row.hidden == true
    entry.fav    = row.fav == true
    entry.manual = row.manual == true
    entry.note   = (type(row.note) == "string" and row.note ~= "") and row.note or nil
  end)

  local hidden, favourites = 0, 0
  for _, entry in ipairs(entries) do
    if not entry.live then
      if entry.manual then
        entry.rank, entry.category = RANK_MANUAL, L["RM_CAT_MANUAL"]
      else
        entry.rank, entry.category = RANK_SAVED, L["RM_CAT_SAVED"]
      end
    end

    -- A stored row already carries its own casing, so Display is cheap for it.
    -- Everything else uses the name the live source gave us.
    if R.Get(entry.key) or not entry.liveName then
      entry.display = R.Display(entry.key)
    else
      entry.display = entry.liveName
    end
    if entry.display == "" then entry.display = entry.key end
    entry.search = Lower(entry.display)
    entry.sortName = entry.search

    local meta = R.AltMeta(entry.key)
    if type(meta) == "table" then
      entry.level    = tonumber(meta.level)
      entry.lastSeen = tonumber(meta.lastSeen)
      entry.faction  = (type(meta.faction) == "string" and meta.faction ~= "") and meta.faction or nil
    end

    entry.stale = StaleFor(entry)

    if entry.hidden then hidden = hidden + 1 end
    if entry.fav then favourites = favourites + 1 end
  end

  return entries, #entries, hidden, favourites
end

-------------------------------------------------------------
-- Filtering and sorting
-------------------------------------------------------------
local function ByName(a, b)
  if a.sortName == b.sortName then return a.key < b.key end
  return a.sortName < b.sortName
end

local function ByNameDesc(a, b)
  if a.sortName == b.sortName then return a.key > b.key end
  return a.sortName > b.sortName
end

-- The value each non-name sort orders by. Unknowns sort below everything in
-- ascending order (and therefore above it when reversed), which is where "no
-- data" belongs in both readings.
local SORT_VALUE = {
  category = function(entry) return entry.rank end,
  level    = function(entry) return entry.level or -1 end,
  lastSeen = function(entry) return entry.lastSeen or 0 end,
}

-- Reversing flips the PRIMARY comparison only; the name tiebreak stays A-Z in
-- both directions. Reversing the whole comparator instead would leave equal
-- levels reading Z-A, which looks like a second, unasked-for sort.
local function Comparator(field, descending)
  local value = SORT_VALUE[field]
  if not value then
    return descending and ByNameDesc or ByName
  end
  if descending then
    return function(a, b)
      local av, bv = value(a), value(b)
      if av ~= bv then return av > bv end
      return ByName(a, b)
    end
  end
  return function(a, b)
    local av, bv = value(a), value(b)
    if av ~= bv then return av < bv end
    return ByName(a, b)
  end
end

local function ActiveCategory()
  return CATEGORY_BY_ID[RM._filter or "all"] or CATEGORY_BY_ID.all
end

local function ApplyFilterAndSort()
  local entries = RM._entries or {}
  local query = Lower(Trim(RM._query or ""))
  local match = ActiveCategory().match
  local filtered = {}

  -- Category and search are one pass and both narrow: the category decides
  -- which names are on the table, the search narrows within them.
  for _, entry in ipairs(entries) do
    if (not match) or match(entry) then
      if query == "" or entry.search:find(query, 1, true) then
        filtered[#filtered + 1] = entry
      end
    end
  end

  table.sort(filtered, Comparator(RM._sort or "name", RM._sortDesc and true or false))
  RM._filtered = filtered
  return filtered
end

-- Per-category totals for the tile tooltips. Six predicates over the entry list
-- is a few thousand comparisons on a big guild -- cheap enough to redo whenever
-- the list changes, and it is the only way the counts can be trusted after a
-- bulk action.
local function CountCategories()
  local counts = {}
  local entries = RM._entries or {}

  for _, category in ipairs(CATEGORIES) do counts[category.id] = 0 end
  counts.all = #entries

  for _, entry in ipairs(entries) do
    for _, category in ipairs(CATEGORIES) do
      if category.match and category.match(entry) then
        counts[category.id] = counts[category.id] + 1
      end
    end
  end

  RM._catCounts = counts
  return counts
end

local function CountStates()
  local hidden, favourites = 0, 0
  for _, entry in ipairs(RM._entries or {}) do
    if entry.hidden then hidden = hidden + 1 end
    if entry.fav then favourites = favourites + 1 end
  end
  return hidden, favourites
end

-- Re-reads hidden/fav straight from the data layer. Used after a bulk action,
-- which is the one path that changes many rows at once without a full rescan.
local function SyncStates()
  local R = Recipients()
  if not R then return end
  for _, entry in ipairs(RM._entries or {}) do
    entry.hidden = R.IsHidden(entry.key)
    entry.fav = R.IsFavorite(entry.key)
    entry.stale = StaleFor(entry)
  end
end

-------------------------------------------------------------
-- Naming the current view
--
-- Every bulk action, tooltip and summary line describes the list the same way,
-- from one place. That matters most in the bulk confirmations: "Hide 148
-- recipients?" is a question nobody can answer safely, whereas "Hide 148
-- recipients? Showing: Guild" is.
-------------------------------------------------------------
local function CategoryLabel(id)
  local category = CATEGORY_BY_ID[id or "all"] or CATEGORY_BY_ID.all
  return L[category.labelKey]
end

-- The summary line does not wrap -- it must not change height, because the list
-- frame is anchored under it -- so the search term it quotes is capped. Cut on
-- a character boundary: chopping a multi-byte sequence in half renders as a
-- broken glyph.
local QUERY_DISPLAY_MAX = 24

local function ShortQuery(text)
  local length = #text
  local index, count = 1, 0
  while index <= length do
    if count == QUERY_DISPLAY_MAX then return text:sub(1, index - 1) .. "..." end
    local byte = text:byte(index)
    local size = 1
    if byte >= 240 then size = 4
    elseif byte >= 224 then size = 3
    elseif byte >= 192 then size = 2 end
    index = index + size
    count = count + 1
  end
  return text
end

-- A phrase naming what narrows the list, or nil when nothing does.
local function ScopeText()
  local query = Trim(RM._query or "")
  local id = RM._filter or "all"

  if id == "all" then
    if query == "" then return nil end
    return L("RM_SCOPE_SEARCH_ALL", ShortQuery(query))
  end
  if query == "" then return CategoryLabel(id) end
  return L("RM_SCOPE_SEARCH", CategoryLabel(id), ShortQuery(query))
end

-- The same phrase, but never nil: an unnarrowed list is "All".
local function ScopePhrase()
  return ScopeText() or CategoryLabel("all")
end

-------------------------------------------------------------
-- Row text
-------------------------------------------------------------
-- A line that appears on every one of several hundred rows has to carry
-- something that VARIES. Anything the whole list shares belongs in the header,
-- the tooltip, or nowhere -- which is why the old "no level or last-played
-- data" placeholder is gone: on a guild account it was three hundred identical
-- copies of a fact that can never change.
local function MetaText(entry)
  local parts = { entry.category or L["RM_CAT_SAVED"] }

  -- Class earns the space the placeholder used to waste: it differs row to row,
  -- and it is the one thing the class-coloured name fails to convey to anyone
  -- who does not already know the colours.
  local class = ClassName(entry.display)
  if class then parts[#parts + 1] = class end

  -- No "Favourites" segment. The star at the head of the row already says it,
  -- in the shape the whole addon uses for that fact, and a row that repeats it
  -- in words spends one of a handful of dense segments -- next to the class, the
  -- level and the last-played time, all of which vary -- restating something the
  -- eye has already read two inches to the left. A fact is stated once.
  if entry.level then parts[#parts + 1] = L("RM_META_LEVEL", entry.level) end
  local last = FormatLastSeen(entry.lastSeen)
  if last then parts[#parts + 1] = L("RM_META_LAST", last) end

  -- Said only where it can come true: one of the player's own characters, which
  -- records itself the next time it is played.
  if not entry.level and not last and TracksActivity(entry) then
    parts[#parts + 1] = L["RM_META_ALT_UNRECORDED"]
  end

  if entry.stale then
    parts[#parts + 1] = Theme.Colorize("warning", L["RM_META_STALE"])
  end

  local text = table.concat(parts, SEPARATOR)
  if entry.note then
    text = text .. "  " .. Theme.Colorize("accent", "\"" .. entry.note .. "\"")
  end
  return text
end

-------------------------------------------------------------
-- Dialogs
-------------------------------------------------------------
local function EnsureAddDialog()
  if type(StaticPopupDialogs) ~= "table" then return false end
  if StaticPopupDialogs[ADD_POPUP] then return true end
  StaticPopupDialogs[ADD_POPUP] = {
    text = "%s",
    button1 = L["RM_ADD_ACCEPT"],
    button2 = L["COD_CONFIRM_CANCEL"],
    hasEditBox = true,
    maxLetters = 64,
    editBoxWidth = 220,
    timeout = 0,
    whileDead = true,
    hideOnEscape = true,
    OnShow = function(self)
      local box = PopupEditBox(self)
      if box then
        box:SetText("")
        box:SetFocus()
      end
    end,
    OnAccept = function(self)
      local box = PopupEditBox(self)
      RM.AddRecipient(box and box:GetText() or "")
    end,
    EditBoxOnEnterPressed = function(self)
      local dialog = self:GetParent()
      local text = self:GetText()
      if dialog and dialog.Hide then dialog:Hide() end
      RM.AddRecipient(text)
    end,
    EditBoxOnEscapePressed = function(self)
      local dialog = self:GetParent()
      if dialog and dialog.Hide then dialog:Hide() end
    end,
  }
  return true
end

local function EnsureNoteDialog()
  if type(StaticPopupDialogs) ~= "table" then return false end
  if StaticPopupDialogs[NOTE_POPUP] then return true end
  StaticPopupDialogs[NOTE_POPUP] = {
    text = "%s",
    button1 = L["RM_NOTE_ACCEPT"],
    button2 = L["COD_CONFIRM_CANCEL"],
    hasEditBox = true,
    maxLetters = 40,
    editBoxWidth = 220,
    timeout = 0,
    whileDead = true,
    hideOnEscape = true,
    OnShow = function(self, data)
      local box = PopupEditBox(self)
      if box then
        box:SetText((type(data) == "table" and data.note) or "")
        box:HighlightText()
        box:SetFocus()
      end
    end,
    OnAccept = function(self, data)
      local box = PopupEditBox(self)
      if type(data) == "table" then
        RM.SetNote(data.key, box and box:GetText() or "")
      end
    end,
    EditBoxOnEnterPressed = function(self)
      local dialog = self:GetParent()
      local text = self:GetText()
      local data = dialog and dialog.data
      if dialog and dialog.Hide then dialog:Hide() end
      if type(data) == "table" then RM.SetNote(data.key, text) end
    end,
    EditBoxOnEscapePressed = function(self)
      local dialog = self:GetParent()
      if dialog and dialog.Hide then dialog:Hide() end
    end,
  }
  return true
end

local function EnsureDeleteDialog()
  if type(StaticPopupDialogs) ~= "table" then return false end
  if StaticPopupDialogs[DELETE_POPUP] then return true end
  StaticPopupDialogs[DELETE_POPUP] = {
    text = "%s",
    button1 = L["RM_DELETE_ACCEPT"],
    button2 = L["COD_CONFIRM_CANCEL"],
    timeout = 0,
    whileDead = true,
    hideOnEscape = true,
    showAlert = true,
    OnAccept = function(_, data)
      if type(data) == "table" then RM.DeleteRecipient(data.key, data.display) end
    end,
  }
  return true
end

local function EnsureBulkDialog()
  if type(StaticPopupDialogs) ~= "table" then return false end
  if StaticPopupDialogs[BULK_POPUP] then return true end
  StaticPopupDialogs[BULK_POPUP] = {
    text = "%s",
    button1 = L["RM_BULK_ACCEPT"],
    button2 = L["COD_CONFIRM_CANCEL"],
    timeout = 0,
    whileDead = true,
    hideOnEscape = true,
    OnAccept = function(_, data)
      if type(data) == "table" then RM.ApplyBulk(data.hide, data.keys) end
    end,
  }
  return true
end

-------------------------------------------------------------
-- Row pool
--
-- Only the rows that fit the viewport exist. Scrolling re-fills them, so the
-- pool never grows past what one screenful needs no matter how many recipients
-- the account has.
-------------------------------------------------------------
-- ONE meaning for right-click-on-a-name, across both windows.
--
-- Right-click favourited in the Send tab's picker and edited a note here, both
-- advertised in their own tooltip -- the same object, the same gesture, two
-- unrelated outcomes, and the single most confusing thing in the feature. It is
-- the frequent action and it is already taught on every picker row, so it wins;
-- notes move to the row's own button, which is where an occasional action with
-- a dialog behind it belongs anyway.
local function ToggleFavorite(entry)
  local R = Recipients()
  if not entry or not R then return end
  local on = not entry.fav
  R.SetFavorite(entry.key, on)
  entry.fav = on
  -- SetFavorite clears hidden by design; mirror it so the row does not have to
  -- wait for a rescan to stop looking hidden.
  if on then entry.hidden = false end
  entry.stale = StaleFor(entry)
  ToggleSound(on)
  RM.SoftRefresh()
end

local function BuildRow(parent)
  local row = CreateFrame("Button", nil, parent)
  row:SetHeight(ROW_H)
  row:RegisterForClicks("RightButtonUp")

  -- The stripe texture is Theme.StyleMailRow's to create and to paint; FillRow
  -- calls it with the row's DISPLAYED position, so this list stripes with the
  -- same warm primitive the mail list and the contact picker use instead of a
  -- flat white wash of its own.
  local highlight = row:CreateTexture(nil, "HIGHLIGHT")
  highlight:SetAllPoints()
  Theme.FillColor(highlight, "stripeHover")

  -- Favourite. Icon-only, so deliberately NOT tagged __postboxButton: the skins
  -- only restyle the addon's push-buttons.
  --
  -- The hit area is larger than the star so the click target is comfortable
  -- without the artwork having to fill it; the star itself is centred at a size
  -- that reads without leaning in.
  row.Fav = CreateFrame("Button", nil, row)
  row.Fav:SetSize(22, 22)
  row.Fav:SetPoint("LEFT", row, "LEFT", 5, 0)
  row.Fav.Icon = row.Fav:CreateTexture(nil, "ARTWORK")
  row.Fav.Icon:SetSize(17, 17)
  row.Fav.Icon:SetPoint("CENTER")
  SetStarArt(row.Fav.Icon, false)
  local favHi = row.Fav:CreateTexture(nil, "HIGHLIGHT")
  favHi:SetAllPoints()
  Theme.FillColor(favHi, "plateHighlight")

  -- Measured, never fixed. This was 64px hard-coded around a caption that comes
  -- out of a locale file, and the German and Russian words for "Delete" are both
  -- wider than the English one -- so it clipped. Constant width plus word wrap
  -- off is exactly the pairing the design system bans.
  row.Delete = Theme.CreateButton(nil, row)
  row.Delete:SetPoint("RIGHT", row, "RIGHT", -6, 0)
  row.Delete:SetText(L["RM_BTN_DELETE"])
  Theme.SizeToText(row.Delete, { minWidth = ROW_BTN_MIN_W, maxWidth = ROW_BTN_MAX_W,
                                 height = ROW_BTN_H })
  -- Without this a disabled button stops firing OnEnter, and the tooltip that
  -- explains WHY it is disabled would never appear.
  if row.Delete.SetMotionScriptsWhileDisabled then
    row.Delete:SetMotionScriptsWhileDisabled(true)
  end

  row.HideLabel = Theme.CreateText(row, "label")
  row.HideLabel:SetPoint("RIGHT", row.Delete, "LEFT", -8, 0)
  row.HideLabel:SetText(L["RM_COL_HIDE"])

  row.HideCheck = CreateFrame("CheckButton", nil, row, "UICheckButtonTemplate")
  row.HideCheck:SetSize(22, 22)
  row.HideCheck:SetPoint("RIGHT", row.HideLabel, "LEFT", -2, 0)
  -- Both tags are required: the skins find the box by __postboxCheck and its
  -- caption by __label.
  row.HideCheck.__postboxCheck = true
  row.HideCheck.__label = row.HideLabel

  -- Notes get an explicit control rather than a hidden gesture. It is a word
  -- and not a glyph for the same reason every other control in this window is:
  -- an unlabelled icon has to be discovered, and this one would be discovered
  -- by right-clicking, which now means something else.
  row.Note = Theme.CreateButton(nil, row)
  row.Note:SetPoint("RIGHT", row.HideCheck, "LEFT", -8, 0)
  row.Note:SetText(L["RM_BTN_NOTE"])
  Theme.SizeToText(row.Note, { minWidth = ROW_BTN_MIN_W, maxWidth = ROW_BTN_MAX_W,
                               height = ROW_BTN_H })

  -- A container so the two text lines can share one right edge without either
  -- of them anchoring across the controls.
  row.TextArea = CreateFrame("Frame", nil, row)
  row.TextArea:SetPoint("TOPLEFT", row, "TOPLEFT", 31, -2)
  row.TextArea:SetPoint("BOTTOM", row, "BOTTOM", 0, 2)
  row.TextArea:SetPoint("RIGHT", row.Note, "LEFT", -8, 0)

  row.Name = Theme.CreateText(row.TextArea, "bodySmall")
  row.Name:SetPoint("TOPLEFT", row.TextArea, "TOPLEFT", 0, 0)
  row.Name:SetPoint("RIGHT", row.TextArea, "RIGHT", 0, 0)
  row.Name:SetJustifyH("LEFT")
  row.Name:SetWordWrap(false)

  -- `secondary`, never the disabled font object: this line carries the
  -- category, the class, the level, the last-played time and the note. It is
  -- the densest line on the row and it is not inactive.
  row.Meta = Theme.CreateText(row.TextArea, "secondary")
  row.Meta:SetPoint("BOTTOMLEFT", row.TextArea, "BOTTOMLEFT", 0, 1)
  row.Meta:SetPoint("RIGHT", row.TextArea, "RIGHT", 0, 0)
  row.Meta:SetJustifyH("LEFT")
  row.Meta:SetWordWrap(false)

  -- Handlers are installed once and read row._entry, so a recycled row never
  -- acts on the recipient it used to show.
  row.Fav:SetScript("OnClick", function()
    ToggleFavorite(row._entry)
  end)
  row.Fav:SetScript("OnEnter", function(self)
    local entry = row._entry
    GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
    GameTooltip:SetText(L["CONTACT_FAVORITES"])
    GameTooltip:AddLine(entry and entry.fav and L["RM_TIP_FAV_ON"] or L["RM_TIP_FAV_OFF"],
                        1, 1, 1, true)
    GameTooltip:Show()
  end)
  row.Fav:SetScript("OnLeave", function() GameTooltip:Hide() end)

  row.HideCheck:SetScript("OnClick", function(self)
    local entry = row._entry
    local R = Recipients()
    if not entry or not R then
      if self.SetChecked then self:SetChecked(false) end
      return
    end
    local on = self:GetChecked() and true or false
    R.SetHidden(entry.key, on)
    entry.hidden = on
    -- SetHidden clears fav by design; mirror it rather than letting the row
    -- keep a star it no longer has.
    if on then entry.fav = false end
    entry.stale = StaleFor(entry)
    ToggleSound(on)
    RM.SoftRefresh()
  end)
  row.HideCheck:SetScript("OnEnter", function(self)
    GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
    GameTooltip:SetText(L["RM_COL_HIDE"])
    GameTooltip:AddLine(L["RM_TIP_HIDE"], 1, 1, 1, true)
    GameTooltip:Show()
  end)
  row.HideCheck:SetScript("OnLeave", function() GameTooltip:Hide() end)

  row.Delete:SetScript("OnClick", function()
    local entry = row._entry
    if entry then RM.ConfirmDelete(entry.key, entry.display) end
  end)
  row.Delete:SetScript("OnEnter", function(self)
    local entry = row._entry
    GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
    GameTooltip:SetText(L["RM_BTN_DELETE"])
    if entry and entry.deleteReason then
      GameTooltip:AddLine(L[entry.deleteReason], 1, 0.5, 0.4, true)
    else
      GameTooltip:AddLine(L["RM_TIP_DELETE"], 1, 1, 1, true)
    end
    GameTooltip:Show()
  end)
  row.Delete:SetScript("OnLeave", function() GameTooltip:Hide() end)

  row.Note:SetScript("OnClick", function()
    local entry = row._entry
    if entry then RM.EditNote(entry.key, entry.display, entry.note) end
  end)
  row.Note:SetScript("OnEnter", function(self)
    local entry = row._entry
    GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
    GameTooltip:SetText(L["RM_BTN_NOTE"])
    GameTooltip:AddLine(L["RM_TIP_NOTE"], 1, 1, 1, true)
    if entry and entry.note then
      GameTooltip:AddLine("\"" .. entry.note .. "\"", 0.83, 0.64, 0.29, true)
    end
    GameTooltip:Show()
  end)
  row.Note:SetScript("OnLeave", function() GameTooltip:Hide() end)

  row:SetScript("OnClick", function(_, button)
    if button == "RightButton" then ToggleFavorite(row._entry) end
  end)
  row:SetScript("OnEnter", function(self)
    local entry = row._entry
    if not entry then return end
    GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
    GameTooltip:SetText(DecorateName(entry.display))
    local head = entry.category or L["RM_CAT_SAVED"]
    local class = ClassName(entry.display)
    if class then head = head .. SEPARATOR .. class end
    GameTooltip:AddLine(head, 0.7, 0.7, 0.7)
    if entry.level then GameTooltip:AddLine(L("RM_META_LEVEL", entry.level), 1, 1, 1) end
    local last = FormatLastSeen(entry.lastSeen)
    if last then GameTooltip:AddLine(L("RM_META_LAST", last), 1, 1, 1) end
    -- The tooltip is where the explanation belongs; the row itself gets the
    -- four-word version, and everyone whose level can never be known gets
    -- neither.
    if not entry.level and not last and TracksActivity(entry) then
      GameTooltip:AddLine(L["RM_TIP_ALT_UNRECORDED"], 0.7, 0.7, 0.7, true)
    end
    if entry.note then GameTooltip:AddLine("\"" .. entry.note .. "\"", 0.83, 0.64, 0.29, true) end
    if entry.stale then GameTooltip:AddLine(L["RM_TIP_STALE"], 1, 0.6, 0.25, true) end
    -- The same gesture, said the same way, as the Send tab's contact picker.
    GameTooltip:AddLine(L["RM_TIP_ROW_FAV"], 0.5, 0.5, 0.5, true)
    GameTooltip:Show()
  end)
  row:SetScript("OnLeave", function() GameTooltip:Hide() end)

  return row
end

local function AcquireRow(index)
  local frame = RM._frame
  local row = RM._rows[index]
  if row then return row, false end
  row = BuildRow(frame.ListChild)
  RM._rows[index] = row
  return row, true
end

-- Resolved on first render and cached on the entry. CanDelete walks the mail
-- history and every saved alt table, which is far too much to pay for several
-- hundred recipients when only a screenful is ever on show. Every path that can
-- change the answer (delete, manual add) rebuilds the entries outright.
local function ResolveDelete(entry)
  if entry.deleteChecked then return end
  entry.deleteChecked = true
  local R = Recipients()
  if not R then
    entry.canDelete, entry.deleteReason = false, "RM_ERR_LIVE_ONLY"
    return
  end
  local canDelete, reason = R.CanDelete(entry.key)
  entry.canDelete = canDelete and true or false
  entry.deleteReason = (not canDelete) and (reason or "RM_ERR_LIVE_ONLY") or nil
end

local function FillRow(row, entry, absoluteIndex)
  row._entry = entry
  ResolveDelete(entry)

  row.Name:SetText(DecorateName(entry.display))
  row.Meta:SetText(MetaText(entry))

  local dim = entry.hidden and 0.45 or 1
  row.Name:SetAlpha(dim)
  row.Meta:SetAlpha(dim)

  SetStarArt(row.Fav.Icon, entry.fav and true or false)

  row.HideCheck:SetChecked(entry.hidden and true or false)

  if entry.canDelete then row.Delete:Enable() else row.Delete:Disable() end

  -- Zebra striping keeps a dense two-line row readable. Painted through the
  -- same primitive the mail list uses, from the row's DISPLAYED position, so
  -- the two lists stripe alike; hover is a HIGHLIGHT texture on this row rather
  -- than a repaint, hence the constant `false`.
  Theme.StyleMailRow(row, absoluteIndex, false)

  row:Show()
end

local function UpdateVisibleRows()
  local frame = RM._frame
  if not frame then return end

  local filtered = RM._filtered or {}
  local scroll = frame.ListScroll
  local viewport = scroll:GetHeight() or 0
  local offset = scroll:GetVerticalScroll() or 0

  local first = math.max(1, math.floor(offset / ROW_H) + 1)
  local last = first - 1
  if viewport > 0 then
    last = math.min(#filtered, math.ceil((offset + viewport) / ROW_H))
  end

  local created = false
  local used = 0
  for index = first, last do
    used = used + 1
    local row, isNew = AcquireRow(used)
    created = created or isNew
    -- TOPLEFT + TOPRIGHT, never LEFT/RIGHT: two corner points on the same edge
    -- fix the width and the top without also constraining the vertical centre,
    -- which would fight SetHeight.
    local y = -((index - 1) * ROW_H)
    row:ClearAllPoints()
    row:SetPoint("TOPLEFT", frame.ListChild, "TOPLEFT", 0, y)
    row:SetPoint("TOPRIGHT", frame.ListChild, "TOPRIGHT", 0, y)
    FillRow(row, filtered[index], index)
  end

  for index = used + 1, #RM._rows do
    local row = RM._rows[index]
    row._entry = nil
    row:Hide()
  end

  -- Rows built on this pass have never been through the skin.
  if created and ns.Skin and ns.Skin.Refresh then
    ns.Skin.Refresh(frame)
  end
end

-- Why a source category is empty, as a locale key, or nil for "no better answer
-- than the generic line".
--
-- ContactService decides it, because it is the only thing that knows whether a
-- guild roster request is still in flight. The Send tab's picker asks the same
-- question of the same function, so the two windows cannot end up explaining the
-- same empty list differently.
local function SourceEmptyReason(source)
  if not source then return nil end
  local CS = ns.ContactService
  if not CS or type(CS.EmptyReason) ~= "function" then return nil end
  local ok, key = pcall(CS.EmptyReason, source)
  if ok and type(key) == "string" and key ~= "" then return key end
  return nil
end

-- What the list says when it has nothing to show. With several hundred
-- recipients an empty list is nearly always a filter the user forgot about, so
-- each case names the thing that emptied it and how to get out.
local function EmptyText(total)
  if total == 0 then return L["RM_EMPTY"] end

  local query = Trim(RM._query or "")
  local id = RM._filter or "all"

  if query ~= "" then
    if id == "all" then return L("RM_EMPTY_SEARCH", ShortQuery(query)) end
    return L("RM_EMPTY_SEARCH_FILTER", ShortQuery(query), CategoryLabel(id))
  end
  if id == "favourites" then return L["RM_EMPTY_FAVOURITES"] end
  if id == "hidden" then return L["RM_EMPTY_HIDDEN"] end
  if id == "all" then return L["RM_EMPTY"] end

  -- "Nothing in Guild" is true and useless to somebody who is not in a guild,
  -- and worse than useless during the roster round trip on a cold login. Where
  -- the reason is knowable it leads, and the way out follows it.
  local category = CATEGORY_BY_ID[id]
  local reason = SourceEmptyReason(category and category.source)
  if reason then return L[reason] .. "\n\n" .. L["RM_EMPTY_FILTER_HINT"] end
  return L("RM_EMPTY_FILTER", CategoryLabel(id))
end

local function UpdateSummary()
  local frame = RM._frame
  if not frame then return end

  local total = #(RM._entries or {})
  local shown = #(RM._filtered or {})
  local hidden, favourites = CountStates()
  local scope = ScopeText()

  if scope then
    frame.Summary:SetText(L("RM_SUMMARY_FILTERED", scope, shown, total, hidden, favourites))
  else
    frame.Summary:SetText(L("RM_SUMMARY", total, hidden, favourites))
  end

  if shown == 0 then
    frame.Empty:SetText(EmptyText(total))
    frame.Empty:Show()
  else
    frame.Empty:Hide()
  end
end

-- Repaints the category tiles: which one is active, and which are empty.
local function UpdateCategoryBar()
  local frame = RM._frame
  if not frame or not frame.CategoryTiles then return end

  local counts = RM._catCounts or {}
  local active = RM._filter or "all"

  for _, tile in ipairs(frame.CategoryTiles) do
    tile._active = (tile._catId == active)
    tile._empty = (counts[tile._catId] or 0) == 0
    if tile._starTile then
      -- Filled gold plus the number when there are favourites, hollow outline
      -- and no number when there are none. The two states then differ in shape,
      -- in colour and in content -- not in how faded the same glyph is.
      SetStarArt(tile.Icon, not tile._empty)
      SetTileCount(tile, counts[tile._catId] or 0)
    end
    StyleTile(tile)
  end

  -- The star tile's width is the word tiles' left edge, so a changed count
  -- re-tiles the rest of the bar.
  if frame.LayoutCategoryBar then frame.LayoutCategoryBar() end

  -- The Send tab's star shows the same count from the same field, and this
  -- window can be open beside an open mailbox. Every path that changes a
  -- favourite comes through here, so this is the one place the other window has
  -- to be told.
  if ns.SendTab and ns.SendTab.RefreshRecipientBar then
    ns.SendTab.RefreshRecipientBar()
  end
end

-- resetScroll: only on a filter/sort change. A hide toggle must not throw the
-- user back to the top of a 300-name list.
local function RelayoutList(resetScroll)
  local frame = RM._frame
  if not frame then return end

  local count = #(RM._filtered or {})
  -- The scroll frame has no width until the window has been laid out once, and
  -- a zero-width child makes every row invisible rather than merely narrow.
  local width = frame.ListScroll:GetWidth() or 0
  if width > 10 then frame.ListChild:SetWidth(width) end
  frame.ListChild:SetHeight(math.max(count * ROW_H, 1))

  -- A category filter can shrink the list under a scroll offset that was valid
  -- a moment ago. The scroll frame keeps that offset, UpdateVisibleRows then
  -- computes a first row past the end of the filtered set, and the viewport
  -- goes blank with a scroll bar that still thinks it has somewhere to go.
  -- Clamp before anything reads the offset.
  local viewport = frame.ListScroll:GetHeight() or 0
  local maxScroll = math.max(0, (count * ROW_H) - viewport)
  if resetScroll then
    frame.ListScroll:SetVerticalScroll(0)
  elseif (frame.ListScroll:GetVerticalScroll() or 0) > maxScroll then
    frame.ListScroll:SetVerticalScroll(maxScroll)
  end

  if frame.ListScroll.UpdateScrollChildRect then frame.ListScroll:UpdateScrollChildRect() end
  UpdateCategoryBar()
  UpdateSummary()
  UpdateVisibleRows()
end

-------------------------------------------------------------
-- Actions
-------------------------------------------------------------

-- State-only redraw: no source rescan, so a checkbox click does not trigger a
-- guild roster pass.
--
-- Under Favourites or Hidden the changed row has just left the list it is
-- sitting in, so those two re-filter instead. Scroll position is kept: the user
-- is working down a list and being thrown back to the top after every tick is
-- worse than the row vanishing under the cursor, which is what they asked for.
function RM.SoftRefresh()
  if not RM._frame then return end

  CountCategories()
  if STATEFUL_FILTERS[RM._filter or "all"] then
    ApplyFilterAndSort()
    RelayoutList(false)
    return
  end

  UpdateCategoryBar()
  UpdateSummary()
  UpdateVisibleRows()
end

function RM.Refresh(resetScroll)
  if not RM._frame then return end
  RM._entries = Collect()
  CountCategories()
  ApplyFilterAndSort()
  RelayoutList(resetScroll)
end

-- Switches the active category. Scroll resets: the list underneath is a
-- different set of names, so keeping the offset would land the user in an
-- arbitrary place in it.
function RM.SetFilter(id)
  local category = CATEGORY_BY_ID[id or "all"]
  if not category then return end
  if RM._filter == category.id then return end
  RM._filter = category.id
  if not RM._frame then return end
  ApplyFilterAndSort()
  RelayoutList(true)
end

-- Sets the sort field, or reverses the direction when the field is already
-- selected. Picking a new field starts it in its own most-useful direction
-- rather than inheriting the previous field's.
function RM.SetSort(id, toggleDirection)
  local sort = SORT_BY_ID[id or "name"]
  if not sort then return end

  if RM._sort == sort.id and toggleDirection then
    RM._sortDesc = not RM._sortDesc
  elseif RM._sort ~= sort.id then
    RM._sort = sort.id
    RM._sortDesc = sort.desc and true or false
  end

  if not RM._frame then return end
  if RM._frame.RefreshSortControl then RM._frame.RefreshSortControl() end
  ApplyFilterAndSort()
  RelayoutList(true)
end

function RM.AddRecipient(text)
  local R = Recipients()
  if not R then
    Notice(L["RM_ERR_NOT_READY"])
    return
  end
  local key, err = R.AddManual(text)
  if not key then
    -- AddManual reports a locale KEY, not a sentence.
    Notice(L[err or "RM_ERR_NOT_READY"])
    return
  end
  -- Clear whatever is narrowing the list so the freshly added name is actually
  -- on screen. A manual add lands under "Added by you" and is favourited, so
  -- any category filter other than Favourites or All would hide it the instant
  -- it was created.
  if RM._frame and RM._frame.SearchBox then RM._frame.SearchBox:SetText("") end
  RM._filter = "all"
  RM.Refresh(true)
  ns.Print(L("RM_ADD_DONE", R.Display(key)))
end

function RM.ConfirmDelete(key, display)
  local R = Recipients()
  if not R or not key then return end
  local canDelete, reason = R.CanDelete(key)
  if not canDelete then
    Notice(L[reason or "RM_ERR_LIVE_ONLY"])
    return
  end
  if not EnsureDeleteDialog() or type(StaticPopup_Show) ~= "function" then
    RM.DeleteRecipient(key, display)
    return
  end
  StaticPopup_Show(DELETE_POPUP, L("RM_DELETE_CONFIRM", display or key), nil,
                   { key = key, display = display })
end

function RM.DeleteRecipient(key, display)
  local R = Recipients()
  if not R or not key then return end
  local removed = R.Delete(key)
  if not (removed and removed.any) then
    ns.Print(L("RM_DELETE_NOTHING", display or key))
  end
  RM.Refresh()
end

function RM.EditNote(key, display, note)
  if not key then return end
  if not EnsureNoteDialog() or type(StaticPopup_Show) ~= "function" then return end
  StaticPopup_Show(NOTE_POPUP, L("RM_NOTE_TITLE", display or key), nil,
                   { key = key, note = note })
end

function RM.SetNote(key, text)
  local R = Recipients()
  if not R or not key then return end
  R.SetNote(key, text)
  RM.Refresh()
end

-- Keys in the current filtered set that the action would actually change.
-- Favourites are never bulk-hidden: SetHidden clears fav by design, and losing
-- a hand-picked favourite to a sweep is not something a bulk button should do.
local function BulkTargets(hide)
  local keys = {}
  for _, entry in ipairs(RM._filtered or {}) do
    if hide then
      if not entry.hidden and not entry.fav then keys[#keys + 1] = entry.key end
    elseif entry.hidden then
      keys[#keys + 1] = entry.key
    end
  end
  return keys
end

function RM.ApplyBulk(hide, keys)
  local R = Recipients()
  if not R or type(keys) ~= "table" then return end
  for _, key in ipairs(keys) do
    R.SetHidden(key, hide and true or false)
  end
  SyncStates()
  RM.SoftRefresh()
end

-- Always confirms, whatever the count.
--
-- The old rule -- confirm above ten, apply silently below it -- was written
-- when the only way to narrow the list was the search box. With a category bar
-- the button under the cursor means something different depending on a tile
-- clicked minutes ago, and the confirmation is the only thing that says which.
-- Naming the scope is the whole point of asking, so asking cheaply is right.
function RM.Bulk(hide)
  local keys = BulkTargets(hide)
  local scope = ScopePhrase()

  if #keys == 0 then
    Notice(L("RM_BULK_NONE", scope))
    return
  end
  if not EnsureBulkDialog() or type(StaticPopup_Show) ~= "function" then
    RM.ApplyBulk(hide, keys)
    return
  end

  -- Snapshot: the search box and the category bar are both still usable while
  -- the dialog is up, so the action must apply to the set the dialog described
  -- rather than to whatever is listed when OK is pressed.
  local msg = hide and L("RM_BULK_HIDE_CONFIRM", #keys, scope)
                    or L("RM_BULK_SHOW_CONFIRM", #keys, scope)
  StaticPopup_Show(BULK_POPUP, msg, nil, { hide = hide, keys = keys })
end

-- Total manageable recipients, for the options-panel button badge.
function RM.Count()
  local _, total = Collect()
  return total or 0
end

-------------------------------------------------------------
-- Build
-------------------------------------------------------------
local function Build()
  if RM._frame then return RM._frame end

  RM._rows = RM._rows or {}
  RM._sort = RM._sort or "name"
  if RM._sortDesc == nil then
    RM._sortDesc = (SORT_BY_ID[RM._sort] and SORT_BY_ID[RM._sort].desc) and true or false
  end
  RM._filter = RM._filter or "all"
  RM._query = RM._query or ""

  -- The global name is required: Helpers.RegisterEscClose puts frame:GetName()
  -- into UISpecialFrames and silently does nothing for an anonymous frame.
  local frame = CreateFrame("Frame", "PostboxRecipientManagerFrame", UIParent,
                            "BasicFrameTemplateWithInset")
  frame:SetSize(DEFAULT_W, DEFAULT_H)
  frame:SetPoint("CENTER", UIParent, "CENTER", 0, 0)
  frame:SetFrameStrata("FULLSCREEN_DIALOG")
  frame:SetToplevel(true)
  frame:SetClampedToScreen(true)
  frame:EnableMouse(true)
  frame:SetMovable(true)
  frame:SetResizable(true)
  if frame.SetResizeBounds then
    frame:SetResizeBounds(MIN_W, MIN_H, MAX_W, MAX_H)
  elseif frame.SetMinResize then
    frame:SetMinResize(MIN_W, MIN_H)
    frame:SetMaxResize(MAX_W, MAX_H)
  end
  frame:RegisterForDrag("LeftButton")
  frame:SetScript("OnDragStart", frame.StartMoving)
  frame:SetScript("OnDragStop", frame.StopMovingOrSizing)
  frame:SetScript("OnMouseDown", function(self) self:Raise() end)
  frame:Hide()

  -- Deliberately no __pbEuiAlwaysOpaque: that exists so the options panel stays
  -- legible while the transparency slider behind it moves. This is a content
  -- window and follows the user's own opacity.
  if frame.TitleText then frame.TitleText:SetText(L["RM_TITLE"]) end
  Theme.ApplyFrameTheme(frame)
  ns.Core.UI.Helpers.RegisterEscClose(frame)

  -----------------------------------------------------------
  -- Header band
  --
  -- Search, sort and the category bar are one enclosed block rather than three
  -- widgets floating over the window's stone. The band is the theme's
  -- `controls` variant -- a quiet warm tint with a lighter border, so it reads
  -- as a divider rather than a panel, but opaque enough to hold the search
  -- text and the tile captions at any window transparency -- and it is tagged
  -- __postboxPanel so a host-UI skin restyles it along with the addon's other
  -- containers.
  -----------------------------------------------------------
  local band = CreateFrame("Frame", nil, frame, "BackdropTemplate")
  band:SetPoint("TOPLEFT", frame, "TOPLEFT", PAD, -28)
  band:SetPoint("TOPRIGHT", frame, "TOPRIGHT", -PAD, -28)
  band:SetHeight((BAND_PAD * 2) + CTRL_H + BAND_PAD + BAR_H)
  Theme.ApplyBand(band)
  frame.HeaderBand = band

  -----------------------------------------------------------
  -- Sort control (Postbox's own dropdown: no MenuUtil, see COMBAT_TAINT.md)
  --
  -- The label used to be a separate "Sort" caption sitting to the left of the
  -- toggle, which read as stray text. It is now inside the toggle -- the button
  -- says "Sort: Name" -- so the control is one object, and the direction lives
  -- in the arrow immediately beside it.
  -----------------------------------------------------------
  local sortGroup = CreateFrame("Frame", nil, band)
  sortGroup:SetSize(SORT_GROUP_W, CTRL_H)
  sortGroup:SetPoint("TOPRIGHT", band, "TOPRIGHT", -BAND_PAD - 1, -BAND_PAD)

  local sortItems = {}
  for index, sort in ipairs(SORTS) do
    sortItems[index] = { id = sort.id, name = L[sort.nameKey] }
  end

  local sortDrop = ns.Core.UI.Dropdown.Create(sortGroup, {
    items        = sortItems,
    toggleWidth  = SORT_TOGGLE_W,
    toggleHeight = SORT_TOGGLE_H,
    height       = CTRL_H,
    defaultId    = RM._sort,
  })
  sortDrop:SetWidth(SORT_TOGGLE_W)
  sortDrop:SetPoint("LEFT", sortGroup, "LEFT", 0, 0)
  frame.SortDropdown = sortDrop

  -- Reversal, the other half of the control. Clicking the arrow flips the
  -- direction; re-picking the field that is already selected flips it too,
  -- which is the idiom every sortable column header in the game uses.
  --
  -- The SAME widget class as the toggle it sits against, not a flat plate. The
  -- two are one control -- "sort by this field, in this direction" -- and a
  -- plate beside a push button reads as two, because on a stock UI the button
  -- carries UIPanelButtonTemplate's bevel and the plate is a flat fill. Same
  -- factory, same height, same __postboxButton tag, so both host-UI skins
  -- restyle the pair together instead of one of them.
  local sortDir = Theme.CreateButton(nil, sortGroup)
  sortDir:SetSize(SORT_DIR_W, SORT_TOGGLE_H)
  sortDir:SetPoint("RIGHT", sortGroup, "RIGHT", 0, 0)

  -- The glyph hangs off a child FRAME rather than off the button, and that is
  -- the whole reason it is visible at all.
  --
  -- Both host-UI skins clear a push button's stock art by sweeping its REGIONS:
  -- Core/Skin_EllesmereUI.lua's Button primitive walks GetRegions() and sets
  -- every texture it finds to alpha 0, and Core/Skin_ElvUI.lua hands the button
  -- to S:HandleButton with strip = true, which is StripTextures. An icon created
  -- on the button IS one of those regions, so from the moment this control
  -- stopped being a plate and became a real button the arrow was wiped the
  -- instant either skin ran -- a blank square with a working tooltip.
  --
  -- A child frame is not a region of its parent, so nothing sweeps it. It is
  -- mouse-transparent (frames take no input unless asked to), so the button
  -- still receives every click and hover. And it draws above every layer of the
  -- parent's art, which on a stock UI also puts the arrow over
  -- UIPanelButtonTemplate's bevel instead of into it.
  local glyph = CreateFrame("Frame", nil, sortDir)
  glyph:SetAllPoints(sortDir)
  -- Stated rather than left to the implicit parent+1: EllesmereUI's border
  -- primitive can add its own overlay frame to a widget it skins, and the glyph
  -- has to stay above whatever a host UI puts on top.
  glyph:SetFrameLevel(sortDir:GetFrameLevel() + 3)
  sortDir.Arrow = glyph:CreateTexture(nil, "OVERLAY")
  sortDir.Arrow:SetSize(SORT_DIR_GLYPH, SORT_DIR_GLYPH)
  sortDir.Arrow:SetPoint("CENTER")
  frame.SortDirection = sortDir

  local function SortDirectionText()
    local pair = SORT_DIRECTION_KEY[RM._sort or "name"] or SORT_DIRECTION_KEY.name
    return L[pair[RM._sortDesc and 2 or 1]]
  end

  -- One place decides what the whole control says, so the toggle caption, the
  -- arrow and the tooltip can never disagree about the current sort.
  function frame.RefreshSortControl()
    local sort = SORT_BY_ID[RM._sort or "name"] or SORTS[1]
    sortDrop:SetSelectedId(sort.id)
    sortDrop:SetText(L("RM_SORT_TOGGLE", L[sort.nameKey]))
    SetArrowArt(sortDir.Arrow, not RM._sortDesc)
    -- After the art, and on every refresh rather than once at build. The glyph
    -- reads as this control's caption, so it takes the caption's loud tone
    -- rather than a warm off-white chosen here -- and a TEXTURE carries no token
    -- for Theme.RepaintAccentText to find, so re-asserting it here is what keeps
    -- it on the LIVE accent after an EllesmereUI user retunes theirs.
    Theme.SetColor(sortDir.Arrow, "accentBright")
  end

  sortDrop:SetChangeCallback(function(id)
    RM.SetSort(id, true)
  end)

  -- SetScript, not the plate factory's `_onEnter` slot: this is a push button
  -- now, and it has no plate art to repaint on hover -- the template's own
  -- highlight does that.
  sortDir:SetScript("OnEnter", function(self)
    GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
    GameTooltip:SetText(L["RM_SORT_LABEL"])
    GameTooltip:AddLine(SortDirectionText(), 1, 1, 1, true)
    GameTooltip:AddLine(L["RM_SORT_DIR_TIP"], 0.7, 0.7, 0.7, true)
    GameTooltip:Show()
  end)
  sortDir:SetScript("OnLeave", function() GameTooltip:Hide() end)
  sortDir:SetScript("OnClick", function()
    RM.SetSort(RM._sort, true)
    ToggleSound(not RM._sortDesc)
  end)

  frame.RefreshSortControl()

  -----------------------------------------------------------
  -- Search box
  -----------------------------------------------------------
  local searchWrap = CreateFrame("Frame", nil, band, "BackdropTemplate")
  searchWrap:SetHeight(CTRL_H)
  searchWrap:SetPoint("TOPLEFT", band, "TOPLEFT", BAND_PAD + 1, -BAND_PAD)
  searchWrap:SetPoint("RIGHT", sortGroup, "LEFT", -8, 0)
  Theme.StyleInput(searchWrap)
  searchWrap.__postboxInputWrap = true

  local searchBox = CreateFrame("EditBox", nil, searchWrap)
  searchBox:SetAutoFocus(false)
  local searchFont = Theme.FontObject("bodySmall")
  if searchFont then searchBox:SetFontObject(searchFont) end
  Theme.SetColor(searchBox, "textPrimary")
  searchBox:SetPoint("TOPLEFT", searchWrap, "TOPLEFT", 8, -4)
  searchBox:SetPoint("BOTTOMRIGHT", searchWrap, "BOTTOMRIGHT", -6, 4)
  -- The wrap carries the backdrop; skinning the inner box as well would double
  -- the border.
  searchBox.__postboxNoEditSkin = true
  searchBox:SetScript("OnEscapePressed", function(self)
    self:SetText("")
    self:ClearFocus()
  end)
  searchWrap:SetScript("OnMouseDown", function() searchBox:SetFocus() end)
  frame.SearchBox = searchBox

  local searchPH = Theme.CreateText(searchWrap, "placeholder")
  searchPH:SetPoint("TOPLEFT", searchWrap, "TOPLEFT", 8, -4)
  searchPH:SetPoint("BOTTOMRIGHT", searchWrap, "BOTTOMRIGHT", -8, 4)
  searchPH:SetJustifyH("LEFT")
  searchPH:SetJustifyV("MIDDLE")
  searchPH:SetText(L["RM_SEARCH_PLACEHOLDER"])

  searchBox:SetScript("OnTextChanged", function(self)
    local text = self:GetText() or ""
    searchPH:SetShown(text == "")
    RM._query = text
    ApplyFilterAndSort()
    RelayoutList(true)
  end)

  -----------------------------------------------------------
  -- Category bar
  --
  -- Favourites is a star tile on the left, exactly as on the Send tab: seven
  -- equal word tiles would take each one to ~65px at the minimum window width,
  -- and these labels do not word-wrap, so a long translation would clip rather
  -- than ellipsize. The remaining six share the rest evenly, and their edges are
  -- derived from the usable width rather than from a rounded per-tile width, so
  -- the last tile always meets the right edge.
  --
  -- The star tile is the one whose width is not fixed: it grows by the width of
  -- its favourite count, at most three characters. That is ~4px off each word
  -- tile at the minimum window size, which those six have to spare -- and it is
  -- read from the tile rather than assumed, so the two can never drift apart.
  -----------------------------------------------------------
  local catBar = CreateFrame("Frame", nil, band)
  catBar:SetHeight(BAR_H)
  catBar:SetPoint("TOPLEFT", searchWrap, "BOTTOMLEFT", 0, -BAND_PAD)
  catBar:SetPoint("RIGHT", sortGroup, "RIGHT", 0, 0)
  frame.CategoryBar = catBar
  frame.CategoryTiles = {}

  local wordTiles = {}

  local function LayoutCategoryBar()
    local width = catBar:GetWidth() or 0
    if width < 60 or #wordTiles == 0 then return end
    -- The star tile's width tracks its favourite count, so read it rather than
    -- assuming the no-count width.
    local left = ((frame.StarTile and frame.StarTile:GetWidth()) or BAR_STAR_W) + BAR_GAP
    local usable = width - left
    local function edge(index)
      return left + math.floor((index * usable / #wordTiles) + 0.5)
    end
    for index, tile in ipairs(wordTiles) do
      tile:ClearAllPoints()
      tile:SetWidth(math.max(1, edge(index) - edge(index - 1) - BAR_GAP))
      tile:SetPoint("TOPLEFT", catBar, "TOPLEFT", edge(index - 1), 0)
    end
  end

  for _, category in ipairs(CATEGORIES) do
    local tile = CreateTile(catBar, "segment")
    tile._catId = category.id

    if category.star then
      tile._starTile = true
      tile:SetWidth(BAR_STAR_W)
      tile:SetPoint("TOPLEFT", catBar, "TOPLEFT", 0, 0)
      tile.Icon = tile:CreateTexture(nil, "ARTWORK")
      tile.Icon:SetSize(BAR_STAR_ICON, BAR_STAR_ICON)
      -- LEFT-anchored rather than centred, so the star does not shift sideways
      -- when a count appears next to it.
      tile.Icon:SetPoint("LEFT", tile, "LEFT", BAR_STAR_PAD, 0)
      -- UpdateCategoryBar picks the real state; this is only the first draw.
      SetStarArt(tile.Icon, false)

      -- Gold, and only on screen when there is something to count. No fixed
      -- width and no wrap: the string sizes itself and the tile is measured
      -- from it, which is the combination that cannot clip. The accent is the
      -- live one, exactly as on the Send tab's star.
      tile.Count = Theme.CreateText(tile, "bodySmall")
      tile.Count:SetPoint("LEFT", tile.Icon, "RIGHT", BAR_COUNT_GAP, 0)
      tile.Count:SetJustifyH("LEFT")
      tile.Count:SetWordWrap(false)
      Theme.SetColor(tile.Count, "accent")
      tile.Count:Hide()
      frame.StarTile = tile
    else
      -- The plate already owns a centred, unwrapped, registered font string in
      -- the `segment` text role, so SetText drives it.
      tile:SetText(L[category.labelKey])
      wordTiles[#wordTiles + 1] = tile
    end

    tile._onEnter = function(self)
      local counts = RM._catCounts or {}
      local count = counts[category.id] or 0
      GameTooltip:SetOwner(self, "ANCHOR_BOTTOM")
      -- The star tile has no label on screen, so the title is the only place
      -- its name is ever said.
      GameTooltip:SetText(L[category.labelKey])
      GameTooltip:AddLine(L("RM_CAT_TIP_COUNT", count, #(RM._entries or {})), 1, 1, 1)
      GameTooltip:AddLine(L["RM_CAT_TIP_HINT"], 0.7, 0.7, 0.7, true)
      -- Empty is not a dead end: say how to fill it.
      if category.star and count == 0 then
        GameTooltip:AddLine(L["RM_CAT_TIP_FAV_EMPTY"], 0.7, 0.7, 0.7, true)
      end
      -- An empty source category says why here too, not only once you have
      -- clicked it and are looking at a blank list.
      if count == 0 and category.source then
        local reason = SourceEmptyReason(category.source)
        if reason then GameTooltip:AddLine(L[reason], 0.7, 0.7, 0.7, true) end
      end
      GameTooltip:Show()
    end
    tile:SetScript("OnClick", function(self)
      RM.SetFilter(self._catId)
      ToggleSound(true)
    end)

    frame.CategoryTiles[#frame.CategoryTiles + 1] = tile
  end

  -- UpdateCategoryBar re-tiles the bar whenever the favourite count changes the
  -- star tile's width, so it needs the layout pass by name.
  frame.LayoutCategoryBar = LayoutCategoryBar
  catBar:SetScript("OnSizeChanged", LayoutCategoryBar)
  LayoutCategoryBar()

  -----------------------------------------------------------
  -- Summary line
  --
  -- Sits between the band and the list because that is what it describes: on a
  -- 300-name account it is the sentence that explains why the list below is
  -- twelve rows long.
  -----------------------------------------------------------
  -- Two top corners, not TOPLEFT + RIGHT: a RIGHT anchor also fixes the
  -- vertical centre, which fights the top and leaves the string's rect
  -- ambiguous -- and the list frame below is anchored to that rect.
  -- `secondary`, not the disabled font object: this sentence is the one that
  -- explains why the list below is twelve rows long, and it is never inactive.
  frame.Summary = Theme.CreateText(frame, "secondary")
  frame.Summary:SetPoint("TOPLEFT", band, "BOTTOMLEFT", 2, -6)
  frame.Summary:SetPoint("TOPRIGHT", band, "BOTTOMRIGHT", -2, -6)
  frame.Summary:SetJustifyH("LEFT")
  frame.Summary:SetWordWrap(false)
  frame.Summary:SetText("")

  -----------------------------------------------------------
  -- Bottom action bar
  -----------------------------------------------------------
  local addButton = Theme.CreateButton(nil, frame)
  addButton:SetHeight(CTRL_H)
  addButton:SetPoint("BOTTOMLEFT", frame, "BOTTOMLEFT", PAD, 10)
  addButton.caption = L["RM_BTN_ADD"]
  addButton:SetText(addButton.caption)
  addButton:SetScript("OnClick", function()
    if not EnsureAddDialog() or type(StaticPopup_Show) ~= "function" then return end
    StaticPopup_Show(ADD_POPUP, L["RM_ADD_TITLE"])
  end)

  -- Right-most control stops short of the resize grip in the corner.
  local showAll = Theme.CreateButton(nil, frame)
  showAll:SetHeight(CTRL_H)
  showAll:SetPoint("BOTTOMRIGHT", frame, "BOTTOMRIGHT", -26, 10)
  showAll.caption = L["RM_BTN_SHOW_ALL"]
  showAll:SetText(showAll.caption)
  showAll:SetScript("OnClick", function() RM.Bulk(false) end)

  local hideAll = Theme.CreateButton(nil, frame)
  hideAll:SetHeight(CTRL_H)
  hideAll:SetPoint("RIGHT", showAll, "LEFT", -ACTION_GAP, 0)
  hideAll.caption = L["RM_BTN_HIDE_ALL"]
  hideAll:SetText(hideAll.caption)
  hideAll:SetScript("OnClick", function() RM.Bulk(true) end)

  -- Measured, and re-measured on resize. All three were 130px wide around
  -- captions that come out of a locale file: "Alle aufgelisteten ausblenden" and
  -- the Russian equivalent are both far wider than "Hide all listed" and simply
  -- ran off the end of the button. LayoutRow evens them to the longest, drops to
  -- the minimum padding if that does not fit, and only then narrows them -- at
  -- which point FitText ellipsizes and the tooltip carries the full caption, so
  -- nothing is ever silently clipped.
  local actionButtons = { addButton, hideAll, showAll }

  local function LayoutActionBar()
    -- PAD at the left, the resize grip's clearance at the right, and one gap of
    -- genuine separation between the add button and the bulk pair.
    local available = (frame:GetWidth() or DEFAULT_W) - PAD - 26 - M.gap
    Theme.LayoutRow(actionButtons, available, {
      height = CTRL_H, gap = ACTION_GAP, maxLines = 1, truncate = true,
      minWidth = M.buttonMinWidth,
    })
    for index = 1, #actionButtons do
      local button = actionButtons[index]
      Theme.FitText(button:GetFontString(), button:GetWidth() - M.gap,
                    button.caption, button)
    end
  end

  frame.LayoutActionBar = LayoutActionBar
  LayoutActionBar()
  -- HookScript: the window persistence layer installs its own size handler and
  -- replacing it would stop the saved size being written.
  frame:HookScript("OnSizeChanged", LayoutActionBar)

  addButton:SetScript("OnEnter", function(self)
    if not self.__pbOverflowText then return end
    GameTooltip:SetOwner(self, "ANCHOR_TOP")
    GameTooltip:ClearLines()
    Theme.AddOverflowLine(self, GameTooltip)
    GameTooltip:Show()
  end)
  addButton:SetScript("OnLeave", function() GameTooltip:Hide() end)

  -- The tooltip names the set the button would act on, because "all listed" is
  -- only meaningful once you know what is currently listed. It reads `caption`
  -- rather than GetText, which may have been ellipsized to fit.
  for _, button in ipairs({ hideAll, showAll }) do
    button:SetScript("OnEnter", function(self)
      GameTooltip:SetOwner(self, "ANCHOR_TOP")
      GameTooltip:SetText(self.caption)
      GameTooltip:AddLine(L("RM_TIP_BULK", #(RM._filtered or {}), ScopePhrase()), 1, 1, 1, true)
      GameTooltip:Show()
    end)
    button:SetScript("OnLeave", function() GameTooltip:Hide() end)
  end

  -----------------------------------------------------------
  -- List
  -----------------------------------------------------------
  local listArea = CreateFrame("Frame", nil, frame, "BackdropTemplate")
  -- Anchored under the summary rather than at a fixed offset, so the header can
  -- change height without a second number needing to be kept in step with it.
  listArea:SetPoint("TOPLEFT", frame.Summary, "BOTTOMLEFT", -2, -6)
  listArea:SetPoint("RIGHT", frame, "RIGHT", -PAD, 0)
  listArea:SetPoint("BOTTOM", addButton, "TOP", 0, 8)
  Theme.ApplyList(listArea)
  frame.ListArea = listArea

  -- UIPanelScrollFrameTemplate specifically: both skins special-case its
  -- classic slider scroll bar.
  local scroll = CreateFrame("ScrollFrame", nil, listArea, "UIPanelScrollFrameTemplate")
  scroll:SetPoint("TOPLEFT", listArea, "TOPLEFT", LIST_INSET, -LIST_INSET)
  -- One gutter width for every scroll frame in the addon, wide enough that the
  -- classic bar clears the container's border art. It was 22 here, which is the
  -- one width that put the bar ON that art.
  scroll:SetPoint("BOTTOMRIGHT", listArea, "BOTTOMRIGHT", -M.scrollGutter, LIST_INSET)
  frame.ListScroll = scroll

  local child = CreateFrame("Frame", nil, scroll)
  child:SetSize(math.max(scroll:GetWidth() or 0, 100), 1)
  scroll:SetScrollChild(child)
  frame.ListChild = child

  -- HookScript, not SetScript: the template installs its own handlers here and
  -- replacing them desynchronises the scroll bar.
  scroll:HookScript("OnSizeChanged", function(self, width)
    if width and width > 10 then child:SetWidth(width) end
    UpdateVisibleRows()
  end)
  scroll:HookScript("OnVerticalScroll", function() UpdateVisibleRows() end)

  frame.Empty = Theme.CreateText(listArea, "secondary")
  frame.Empty:SetPoint("TOPLEFT", listArea, "TOPLEFT", 24, -40)
  frame.Empty:SetPoint("BOTTOMRIGHT", listArea, "BOTTOMRIGHT", -24, 24)
  frame.Empty:SetJustifyH("LEFT")
  frame.Empty:SetJustifyV("TOP")
  frame.Empty:SetWordWrap(true)
  frame.Empty:Hide()

  -----------------------------------------------------------
  -- Position / size persistence
  -----------------------------------------------------------
  local store = ns.Store.EnsurePath("profile.rmWindow", {})
  -- The header grew a row, so the minimum window height did too. A size stored
  -- under the old floor would be restored verbatim (persistence clamps on save,
  -- not on restore) and hand back a two-row list; raise it here instead.
  if type(store.width) == "number" and store.width < MIN_W then store.width = MIN_W end
  if type(store.height) == "number" and store.height < MIN_H then store.height = MIN_H end

  frame.ResizeButton = ns.Core.UI.Helpers.CreateResizeButton(frame, function(f)
    ns.Core.UI.Helpers.SaveFramePosition(f, store)
    UpdateVisibleRows()
  end)
  -- After the frame's own OnDragStop is set: ApplyWindowPersistence wraps it.
  ns.Core.UI.Helpers.ApplyWindowPersistence(frame, store, {
    minW = MIN_W, maxW = MAX_W, minH = MIN_H, maxH = MAX_H,
  })

  RM._frame = frame

  -- ApplyWindow only exists in the EllesmereUI skin; without the Apply fallback
  -- ElvUI users would get an unskinned window.
  if ns.Skin then (ns.Skin.ApplyWindow or ns.Skin.Apply)(frame) end

  return frame
end

-------------------------------------------------------------
-- Public API
-------------------------------------------------------------
function RM.Show()
  local frame = Build()
  if not frame:IsShown() then
    -- Never leave the sort list and the Send tab's contact picker open at once.
    if ns.Core.UI.Dropdown and ns.Core.UI.Dropdown.CloseAll then
      ns.Core.UI.Dropdown.CloseAll()
    end
    frame:Show()
  end
  RM.Refresh()
  frame:Raise()
  if ns.Skin and ns.Skin.Refresh then ns.Skin.Refresh(frame) end
end

function RM.Hide()
  if RM._frame then RM._frame:Hide() end
end

function RM.IsShown()
  return RM._frame ~= nil and RM._frame:IsShown()
end

function RM.Toggle()
  local frame = Build()
  if frame:IsShown() then
    frame:Hide()
    return
  end
  RM.Show()
end
